import assert from 'node:assert/strict';
import test from 'node:test';
import {calculateEstimateEntry,calculateEstimateSummary,estimateOverrideReport,estimateManualFields,newEstimateData,performanceBondAmount} from '../app/estimate-template.ts';
import {scenarios,makeEstimate,putCell,verifyEstimate,cash,quantityRules} from './support/estimating-scenarios.mjs';

test('100 independently calculated cap sheets retain formulas through quantity, rates, fees and reloads',()=>{for(const s of scenarios()){let e=makeEstimate(s);e=putCell(e,s.tradeCode,'subcontract',200+s.quote+s.secondQuote);verifyEstimate(s,e);const doubled={...s,months:s.months*2,q:s.q+3};let changed={...e,projectInputs:{...e.projectInputs,projectDurationMonths:doubled.months}};for(const key of Object.keys(quantityRules))changed=putCell(changed,key,'quantity',doubled.q);verifyEstimate(doubled,changed);assert.deepEqual(estimateManualFields(e,'0131.00:100'),['equipment']);const pm=calculateEstimateEntry(changed,'0131.00','100',{quantity:0,unit:'HR'}).entry;assert.equal(pm.equipment,7.5);assert.equal(pm.labor,cash(doubled.months*80*s.pmCost));}});

test('summary fee cell overrides preserve other automatic cells and report all setup overrides',()=>{let e=newEstimateData();e.projectInputs.projectDurationMonths=3;e=putCell(e,'0143.00','equipment',25);const first=calculateEstimateSummary(e);e.projectInputs.projectDurationMonths=6;const next=calculateEstimateSummary(e);assert.ok(next.baseProfit>first.baseProfit);assert.equal(next.baseProfit,cash(next.directJobCost*.1+25));e.projectInputs.cleanupFeeOverride=0;e.projectInputs.architecturalFeeOverride=0;e.settings.projectManagerBillableRate=140;const report=estimateOverrideReport(e);for(const key of ['0143.00','projectInputs.cleanupFeeOverride','projectInputs.architecturalFeeOverride','settings.projectManagerBillableRate'])assert.ok(report.some(item=>item.lineKey===key),key);});

test('legacy manual rows keep their approved values and reset restores formulas',()=>{const e=newEstimateData();e.entries['0131.00:100']={quantity:100,unit:'HR',material:0,labor:6500,equipment:0,subcontract:0,other:5500};e.projectInputs.projectDurationMonths=24;assert.equal(calculateEstimateEntry(e,'0131.00','100',{quantity:0,unit:'HR'}).entry.labor,6500);delete e.entries['0131.00:100'];assert.equal(calculateEstimateEntry(e,'0131.00','100',{quantity:0,unit:'HR'}).entry.labor,124800);});

test('bond tier boundaries and numeric credits remain exact to cents',()=>{for(const [amount,expected]of [[0,0],[99999.99,2500],[100000,2500],[100000.01,2500],[500000,8500],[500000.01,8500],[1500000,18500]])assert.equal(performanceBondAmount(amount),expected);});

test('new fee detail adjustments enter the selling price without double counting the parent fee',()=>{let e=newEstimateData();e.projectInputs.architecturalFeeOverride=0;const original=calculateEstimateSummary(e);e=putCell(e,'0143.00:200','other',123.45);const updated=calculateEstimateSummary(e);assert.equal(updated.baseProfit,cash(original.baseProfit+123.45));assert.equal(calculateEstimateEntry(e,'0143.00',undefined,{quantity:1,unit:'LS'}).entry.other,original.baseProfit);assert.equal(updated.contractValue,cash(original.directJobCost+original.baseProfit+123.45+cash((original.directJobCost+original.baseProfit+123.45)*.001)));});
