import assert from 'node:assert/strict';
import test from 'node:test';
import {mkdtemp,writeFile,rm,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {execFileSync} from 'node:child_process';
import {PDFDocument,StandardFonts} from 'pdf-lib';
import {zipSync,unzipSync,strFromU8,strToU8} from 'fflate';
import {harness,owner,today} from './support/project-workflow-harness.mjs';
import {activateActor} from './support/f06-runtime-harness.mjs';
import {extractQuoteFields} from '../lib/quote-ocr.js';
import {estimateOverrideReport} from '../app/estimate-template.ts';
import {scenarios,makeEstimate,verifyEstimate,cash,SEED} from './support/estimating-scenarios.mjs';
const estimator={name:'Morgan Estimating Audit',email:'estimating.only@example.invalid',accessLevel:'Employee',designations:['Estimator']};
const approvedChecks=amount=>({scopeComplete:true,exclusionsReviewed:true,alternatesReviewed:true,clarificationsComplete:true,budgetCompared:true,leveledAmount:amount,notes:'Checked original scope, exclusions, alternates, lead time and budget individually.',scopeResolution:''});
async function quoteFile(folder,name,price,scope,exclusions){const pdf=await PDFDocument.create();const font=await pdf.embedFont(StandardFonts.Helvetica);let page=pdf.addPage([612,792]),y=750;const lines=[`SYNTHETIC TEST ONLY - ${name}`,'Project reference: 20260911','Scope of Work:',...scope.split('\n'),'Exclusions:',exclusions||'None',`Grand Total: $${price.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`];for(const line of lines){if(y<60){page=pdf.addPage([612,792]);y=750;}page.drawText(line,{x:40,y,size:11,font});y-=22;}const bytes=await pdf.save();const path=`${folder}/${name}.pdf`;await writeFile(path,bytes);const text=execFileSync('pdftotext',['-layout',path,'-'],{encoding:'utf8'});const extracted=extractQuoteFields(text);assert.equal(extracted.price,price,`PDF extraction ${name}`);for(const line of scope.split('\n'))assert.ok(extracted.scope.includes(line),`Scope line ${line} must survive PDF extraction`);assert.ok(!extracted.scope.includes('Grand Total'));return {bytes,extracted};}
function editWord(bytes,id){const files=unzipSync(bytes);let found=false;files['word/document.xml']=strToU8(strFromU8(files['word/document.xml']).replace(/<w:sdt>[\s\S]*?<\/w:sdt>/g,block=>{if(!block.includes('w:val="meffcon:executiveSummary"'))return block;found=true;return block.replace(/<w:sdtContent>[\s\S]*?<\/w:sdtContent>/,`<w:sdtContent><w:p><w:r><w:t>Estimating scope confirmed for ${id}. Coordinate owner access and utility interruptions.</w:t></w:r></w:p></w:sdtContent>`);}));assert.ok(found);return zipSync(files);}

test('100 estimating-only projects preserve quote evidence, cap sheet math, scope, review, Word changes and owner delivery', {timeout:300000},async t=>{
 const h=await harness(),folder=await mkdtemp(`${tmpdir()}/meffcon-estimating-`),results=[],guards=[],deliveries=[];const started=Date.now();let currentId='';
 await h.runtime.database.prepare("INSERT INTO company_members (email,display_name,company_access_level,designations_json,is_active,identity_provider,provider_subject) VALUES (?,?,?,?,1,'f06_test_identity',?)").bind(estimator.email,estimator.name,estimator.accessLevel,JSON.stringify(estimator.designations),estimator.email).run();await activateActor(h.runtime.database,estimator);h.runtime.database.maxBindings=100;
 const vendors=[];for(let i=0;i<3;i++){const v=await h.post('/api/procurement',{action:'create-prospective-vendor',scope:'Sales',legalName:`SYNTHETIC Electrical Bidder ${i+1}`,contactName:`Synthetic Contact ${i+1}`,contactEmail:`quote-${i+1}@example.invalid`,trade:'Electrical'},estimator,201);vendors.push(v.vendorId);}
 const basePost=(action,payload={},actor=estimator,status=200)=>h.post('/api/procurement',{action,scope:'Sales',...payload},actor,status);
 async function intake(recordId,vendorId,price,scope,exclusions='',suffix='quote',acknowledgedAddenda=[]){const fixture=await quoteFile(folder,`${currentId}-${suffix}`,price,scope,exclusions);const form=new FormData();form.set('projectId',`ESTIMATE-${currentId}`);form.set('category','03-Estimating - Quotes');form.set('revision',`${recordId} ${suffix} original`);form.set('access','Internal Procurement');form.set('file',new File([fixture.bytes],`${suffix}.pdf`,{type:'application/pdf'}));const upload=await h.post('/api/files',form,estimator,201);const q={fileId:upload.file.id,confirmed:true,reviewedPrice:fixture.extracted.price,reviewedScope:fixture.extracted.scope,extractedPrice:fixture.extracted.price,extractedScope:fixture.extracted.scope,characterCount:fixture.extracted.characterCount,exclusions,alternates:'None',clarifications:'Normal working hours; six-week lead time confirmed',schedule:'Six weeks',acknowledgedAddenda};const recorded=await basePost('record-quote',{recordId,vendorId,quote:q},estimator,201);const stored=await h.send(`/api/files?id=${upload.file.id}`,{actor:estimator,binary:true});assert.deepEqual(stored,fixture.bytes,'Original quote bytes retained');return {...recorded,quote:q};}
 try{for(const s of scenarios()){const fullScope=s.scopeLines.join('\n');currentId=s.id;let step='new estimate';const before=h.calls();try{
 const opp={projectName:`SYNTHETIC Estimating ${s.id}`,company:['SYNTHETIC City Government','SYNTHETIC Summit Properties','SYNTHETIC Cardinal Manufacturing'][s.index%3],contactId:'',contactName:'Synthetic Owner Representative',contactEmail:`owner-${s.index+1}@example.invalid`,assignedEstimator:estimator.name,stage:'Estimating',directEstimate:true,leadSource:s.index%2?'Referral':'Public Bid',ownerContractType:s.index%2?'Design-Build GMP':'Plan & Spec Lump Sum',deliveryMethod:s.index%2?'Design-Build GMP':'Plan & Spec Lump Sum',projectType:'Commercial',projectLocation:'200 Synthetic Way, Lexington, KY 40507',projectAddress:'200 Synthetic Way, Lexington, KY 40507',projectDescription:fullScope,expectedAwardDate:today,targetStartDate:today,estimatedValue:'0',probability:'50'};
 await h.save('MEFFORD-SALES','Sales Opportunities',s.id,'Estimating',opp,estimator,201,{title:opp.projectName});let estimate=makeEstimate(s);verifyEstimate(s,estimate,0);await h.save('MEFFORD-SALES','Sales Opportunities',s.id,'Estimating',{...h.row('MEFFORD-SALES',s.id).data,estimate,estimateStatus:'In Progress'},estimator);
 step='original quote intake and scope comparison';const created=await basePost('create-package',{opportunityId:s.id,title:`${s.trade} ${s.id}`,trade:s.trade,costCode:s.tradeCode,scopeDescription:fullScope,scopeNature:'Labor And Material',budgetAmount:s.quote,deadline:'2099-12-31T17:00:00Z'},estimator,201);const packageId=created.recordId;
 for(let i=0;i<3;i++){const price=i===0?(s.index===0?850:cash(s.quote*.8)):i===1?s.quote:cash(s.quote*1.15);await intake(packageId,vendors[i],price,i===0?s.scopeLines.slice(0,2).join('\n'):fullScope,i===0?s.scopeLines[2]:i===1?s.exclusion:'',`bidder-${i}`);await basePost('update-leveling',{recordId:packageId,vendorId:vendors[i],leveling:approvedChecks(price)});}
 const comparison=(await h.send('/api/procurement?scope=Sales',{actor:estimator})).packages.find(p=>p.id===packageId).review;assert.equal(comparison.lowestQuoted.vendorId,vendors[0]);assert.equal(comparison.recommended.vendorId,vendors[1]);assert.ok(comparison.quotes.find(q=>q.vendorId===vendors[0]).issues.some(item=>item.includes('scope requirement')));await basePost('select-proposal-basis',{recordId:packageId,vendorId:vendors[0]},estimator,409);
 step='estimate quote handoff';await basePost('select-proposal-basis',{recordId:packageId,vendorId:vendors[1]});await basePost('select-proposal-basis',{recordId:packageId,vendorId:vendors[1]});assert.equal(h.row('MEFFORD-SALES',s.id).data.estimate.entries[s.tradeCode].subcontract,cash(200+s.quote),'reselecting the same bid is not additive');
 if(s.secondQuote){const second=await basePost('create-package',{opportunityId:s.id,title:`Controls ${s.id}`,trade:`${s.trade} Coordination`,costCode:s.tradeCode,scopeDescription:'Control panel programming',scopeNature:'Labor And Material',budgetAmount:s.secondQuote,deadline:'2099-12-31T17:00:00Z'},estimator,201);await intake(second.recordId,vendors[2],s.secondQuote,'Control panel programming','','controls');await basePost('update-leveling',{recordId:second.recordId,vendorId:vendors[2],leveling:approvedChecks(s.secondQuote)});await basePost('select-proposal-basis',{recordId:second.recordId,vendorId:vendors[2]});assert.equal(Object.keys(h.row('MEFFORD-SALES',s.id).data.estimateSourceSelections).length,2,'Two packages using the same cost code retain separate sources');}
 estimate=h.row('MEFFORD-SALES',s.id).data.estimate;const summary=verifyEstimate(s,estimate);assert.equal(estimate.status,'Draft');
 if(s.index===0){const beforeState=JSON.stringify(h.row('MEFFORD-SALES',s.id));h.runtime.database.injectFailure({pattern:/UPDATE command_records SET data_json=\?,status=/});await basePost('select-proposal-basis',{recordId:packageId,vendorId:vendors[2]},estimator,409);assert.equal(JSON.stringify(h.row('MEFFORD-SALES',s.id)),beforeState,'selection rollback leaves estimate intact');assert.equal(h.runtime.database.one('SELECT COUNT(*) count FROM estimate_write_guards').count,0);guards.push('atomic selection rollback','lowest incomplete quote blocked','repeat selection is idempotent','multiple packages on same cost code add correctly');}
 step='estimate review';estimate={...estimate,status:'Ready For Review',submittedAt:new Date().toISOString(),submittedOverrideReport:estimateOverrideReport(estimate),savedAt:new Date().toISOString(),savedBy:estimator.name};await h.save('MEFFORD-SALES','Sales Opportunities',s.id,'Estimating',{...h.row('MEFFORD-SALES',s.id).data,estimate,estimateStatus:'Ready For Review'},estimator);await h.post('/api/owner-approvals',{action:'decide',approvalItemId:`estimate:MEFFORD-SALES:${s.id}`,decision:'Approved',note:'Synthetic cap sheet independently reconciled'},owner);verifyEstimate(s,h.row('MEFFORD-SALES',s.id).data.estimate);
 step='proposal scope and Word roundtrip';const generated=await h.post('/api/proposals',{action:'generate',opportunityId:s.id,packetType:'Construction Proposal'},estimator,201);let proposal={...generated.record.data,ownerContactName:'Synthetic Owner Representative',ownerContactEmail:opp.contactEmail,targetStartDate:today,projectLocation:opp.projectLocation};assert.equal(proposal.contractPrice,summary.contractValue);assert.equal(proposal.durationMonths,s.months);assert.equal(proposal.sourceSnapshot.selectedQuoteCount,s.secondQuote?2:1);assert.ok(proposal.scopeSections.some(x=>x.description.includes(s.scopeLines[2])));assert.ok(proposal.exclusions.some(x=>x.includes(s.exclusion)));const safeSaved=await h.post('/api/proposals',{action:'save',opportunityId:s.id,packetType:'Construction Proposal',data:{...proposal,ownerDelivery:{status:'Provider Accepted',revision:proposal.revision,receiptId:'forged'},sourceSnapshot:{...proposal.sourceSnapshot,estimateContractValue:0,estimateCalculationSignature:'forged'}}},estimator);assert.equal(safeSaved.record.data.ownerDelivery,undefined,'delivery evidence cannot be supplied by the editor');assert.equal(safeSaved.record.data.sourceSnapshot.estimateContractValue,summary.contractValue,'source evidence cannot be supplied by the editor');const word=await h.send(`/api/proposals/document?opportunityId=${s.id}&recordId=${generated.record.id}&format=docx`,{actor:estimator,binary:true});const edited=editWord(word,s.id),wordForm=new FormData();wordForm.set('action','import-word');wordForm.set('opportunityId',s.id);wordForm.set('packetType','Construction Proposal');wordForm.set('file',new File([edited],'Estimating-Proposal-Edited.docx',{type:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}));proposal=(await h.post('/api/proposals',wordForm,estimator)).record.data;assert.ok(proposal.executiveSummary.includes(s.id));assert.equal(proposal.contractPrice,summary.contractValue);
 if(s.index===0){await mkdir('tests/fixtures/estimating-pressure',{recursive:true});await writeFile('tests/fixtures/estimating-pressure/edited-proposal.docx',edited);await writeFile('tests/fixtures/estimating-pressure/cap-sheet.json',JSON.stringify({scenario:s,estimate:h.row('MEFFORD-SALES',s.id).data.estimate,expected:summary},null,2));}
 step='proposal review and issue';await h.post('/api/proposals',{action:'issue',opportunityId:s.id,packetType:'Construction Proposal'},owner,409);await h.post('/api/proposals',{action:'submit-review',opportunityId:s.id,packetType:'Construction Proposal',data:proposal},estimator);await h.post('/api/owner-approvals',{action:'decide',approvalItemId:`owner-proposal:MEFFORD-SALES:${generated.record.id}`,decision:'Approved',note:'Synthetic quote scope, exceptions and Word edits reviewed'},owner);
 if(s.index===0){await intake(packageId,vendors[1],s.quote,fullScope,s.exclusion,'revised-bid');await h.post('/api/proposals',{action:'issue',opportunityId:s.id,packetType:'Construction Proposal'},owner,409);await basePost('update-leveling',{recordId:packageId,vendorId:vendors[1],leveling:approvedChecks(s.quote)});await basePost('select-proposal-basis',{recordId:packageId,vendorId:vendors[1]});const latestEstimate=h.row('MEFFORD-SALES',s.id).data.estimate;await h.save('MEFFORD-SALES','Sales Opportunities',s.id,'Estimating',{...h.row('MEFFORD-SALES',s.id).data,estimate:{...latestEstimate,status:'Ready For Review'},estimateStatus:'Ready For Review'},estimator);await h.post('/api/owner-approvals',{action:'decide',approvalItemId:`estimate:MEFFORD-SALES:${s.id}`,decision:'Approved',note:'Revised quote checked'},owner);await h.post('/api/proposals',{action:'issue',opportunityId:s.id,packetType:'Construction Proposal'},owner,409);proposal=(await h.post('/api/proposals',{action:'refresh',opportunityId:s.id,packetType:'Construction Proposal'},estimator)).record.data;await h.post('/api/proposals',{action:'submit-review',opportunityId:s.id,packetType:'Construction Proposal',data:proposal},estimator);await h.post('/api/owner-approvals',{action:'decide',approvalItemId:`owner-proposal:MEFFORD-SALES:${generated.record.id}`,decision:'Approved',note:'Revised quote and refreshed proposal checked'},owner);guards.push('revised quote blocks previously approved proposal','new revision requires fresh leveling, estimate and proposal approval');}
 const issued=await h.post('/api/proposals',{action:'issue',opportunityId:s.id,packetType:'Construction Proposal'},owner);assert.equal(issued.record.data.status,'Issued');const pdf=await h.send(`/api/proposals/document?opportunityId=${s.id}&recordId=${generated.record.id}`,{actor:estimator,binary:true});assert.equal(Buffer.from(pdf).subarray(0,4).toString(),'%PDF');
 step='project owner submission';const deferred=await h.post('/api/proposals',{action:'send-owner',opportunityId:s.id,packetType:'Construction Proposal',confirmedRecipient:opp.contactEmail},owner);assert.equal(deferred.delivery.status,'Deferred');assert.ok(deferred.delivery.error);const blockedFetch=globalThis.fetch;h.runtime.env.OPERATIONAL_EMAIL_WEBHOOK_URL='https://synthetic-delivery.example.invalid';globalThis.fetch=async (url,options)=>{assert.equal(String(url),'https://synthetic-delivery.example.invalid');const sent=JSON.parse(options.body);assert.equal(sent.to,opp.contactEmail);assert.deepEqual(Buffer.from(sent.attachments[0].base64,'base64'),Buffer.from(pdf));assert.equal(sent.attachments[0].contentType,'application/pdf');deliveries.push({id:s.id,recipient:sent.to,attachmentBytes:pdf.length});return new Response(JSON.stringify({receiptId:`synthetic-${s.id}`}),{status:202,headers:{'content-type':'application/json'}});};try{const sent=await h.post('/api/proposals',{action:'send-owner',opportunityId:s.id,packetType:'Construction Proposal',confirmedRecipient:opp.contactEmail},owner);assert.equal(sent.delivery.status,'Provider Accepted');await h.post('/api/proposals',{action:'send-owner',opportunityId:s.id,packetType:'Construction Proposal',confirmedRecipient:opp.contactEmail},owner);assert.equal(deliveries.filter(x=>x.id===s.id).length,1);}finally{globalThis.fetch=blockedFetch;delete h.runtime.env.OPERATIONAL_EMAIL_WEBHOOK_URL;}
 verifyEstimate(s,h.row('MEFFORD-SALES',s.id).data.estimate);assert.equal(h.row('MEFFORD-SALES',s.id).data.stage,'Proposal Submitted');results.push({id:s.id,trade:s.trade,costCode:s.tradeCode,passed:true,requests:h.calls()-before,contractValue:summary.contractValue,quoteFiles:3+(s.secondQuote?1:0)+(s.index===0?1:0),scopeRequirements:3,delivery:'Synthetic adapter accepted exact issued PDF; duplicate request did not resend'});
 }catch(error){results.push({id:s.id,passed:false,step,error:error.message,requests:h.calls()-before});if(process.env.ESTIMATING_TRACE)console.log(results.at(-1));}if(results.length%10===0)t.diagnostic(`${results.length}/100 exercised; ${results.filter(r=>r.passed).length} passed`);}
 }finally{const report={seed:SEED,runAt:new Date().toISOString(),runtime:process.env.LIFECYCLE_SOURCE==='1'?'source handlers':'compiled Worker',durationSeconds:cash((Date.now()-started)/1000),projects:results.length,passed:results.filter(r=>r.passed).length,failed:results.filter(r=>!r.passed).length,requests:h.calls(),deliveryReceipts:deliveries.length,realMessagesSent:0,guards,results};await writeFile('docs/estimating-pressure-results-2026-09-11.json',JSON.stringify(report,null,2)+'\n');await rm(folder,{recursive:true,force:true});await h.close();}
 assert.equal(results.length,100);assert.equal(results.filter(r=>!r.passed).length,0,JSON.stringify(results.filter(r=>!r.passed).slice(0,3),null,2));assert.equal(deliveries.length,100);
});
