"use client";
import type { DailyScheduleActivity, DailyScheduleConfirmation } from "../lib/daily-schedule";

export function DailyScheduleCheck({ activities, confirmations, onChange, date }: { activities: DailyScheduleActivity[]; confirmations: Partial<DailyScheduleConfirmation>[]; onChange: (rows: Partial<DailyScheduleConfirmation>[]) => void; date: string }) {
  function update(activity: DailyScheduleActivity, patch: Partial<DailyScheduleConfirmation>) { onChange([...confirmations.filter(item => item.id !== activity.id), { ...activity, ...confirmations.find(item => item.id === activity.id), ...patch }]); }
  return <details className="field-section" open><summary>Schedule Check · {confirmations.filter(item => item.status && item.timing).length}/{activities.length} Confirmed</summary><div className="field-section-body">{!activities.length ? <p className="field-source">No Planned Or Overdue Activities For This Date.</p> : activities.map(activity => {
    const answer = confirmations.find(item => item.id === activity.id);
    const completeDate = answer?.completedDate || date;
    const behind = answer?.status === "Complete" ? completeDate > activity.finish : date > activity.finish || (answer?.status === "Not Started" && date > activity.start);
    return <article className="field-schedule-activity" key={activity.id}><h3>{activity.title}</h3><p>{activity.trade} · {activity.start} – {activity.finish}</p><div className="field-answer-row" role="group" aria-label={`${activity.title}: Progress`}>{(["Not Started", "In Progress", "Complete"] as const).map(status => <button type="button" key={status} aria-pressed={answer?.status === status} onClick={() => update(activity, { status, ...(status === "Complete" ? { completedDate: date } : { completedDate: "" }) })}>{status}</button>)}</div>{answer?.status === "Complete" ? <label className="field-label">Completed On<input type="date" max={date} value={completeDate} onChange={event => update(activity, { completedDate: event.target.value })} /></label> : null}<div className="field-answer-row" role="group" aria-label={`${activity.title}: Timing`}>{(["On Track", "Delayed"] as const).map(timing => <button type="button" key={timing} disabled={timing === "On Track" && behind} aria-pressed={(behind && answer?.status ? "Delayed" : answer?.timing) === timing} onClick={() => update(activity, { timing })}>{timing}</button>)}</div>{behind || answer?.timing === "Delayed" ? <label className="field-label">Delay Reason<textarea rows={2} value={answer?.reason || ""} onChange={event => update(activity, { reason: event.target.value, timing: "Delayed" })} placeholder="What Is Holding Up The Work?" /></label> : null}</article>;
  })}</div></details>;
}
