import { useState } from "react";

type PreviewProps = {
  projectName: string;
  projectNumber: string;
  subcontractDate: string;
  constructionSite: string;
  ownerName: string;
  ownerContractDate: string;
  architect: string;
  subcontractor: string;
  signerName: string;
  signerTitle: string;
  signerEmail: string;
  price: string;
  retainage: string;
  substantialDate: string;
  finalDate: string;
  cglLimit: string;
  workersCompLimit: string;
  liquidatedDamages: string;
  scope: string;
  proposalName: string;
  onClose: () => void;
};

type Clause = { title: string; body: string };

const agreementPages: Clause[][] = [
  [
    { title: "1. Incorporation by Reference of Contract Documents; Interpretation of Documents.", body: "1.1 The Contract Documents are incorporated in this Subcontract by reference and made a part hereof. If any provision of this Subcontract conflicts or is inconsistent with a provision of the Contract Documents, or if there is a conflict or inconsistency within this Subcontract or within any of the Contract Documents, the Contract Documents govern. Subcontractor is bound by all interpretations of the Contract Documents made by the Owner or the Architect/Engineer and furnished to it by General Contractor that are binding upon General Contractor." },
    { title: "2. Statement of Subcontractor’s Work.", body: "2.1 Subcontractor shall perform and furnish all work, labor, materials, equipment, tools, and all other services and facilities necessary to complete the Subcontractor’s Work as specified in Exhibit A of this Subcontract. Subcontractor shall not interfere in any way with the Owner’s business operations. Subcontractor is responsible for all permits, fees, licenses, assessments, inspections, testing, and taxes necessary to complete Subcontractor’s Work.\n\n2.2 Subcontractor’s Work shall be performed in accordance with the requirements of this Subcontract and the Contract Documents. With respect to Subcontractor’s Work, General Contractor and Subcontractor agree to be bound by all of the terms and provisions of the Contract Documents and to assume toward General Contractor all of the duties, obligations and responsibilities that General Contractor by those Contract Documents assumes toward the Owner. General Contractor shall have the benefit of all rights, remedies, and redress against Subcontractor that the Owner under the Contract Documents, has against General Contractor.\n\n2.3 Subcontractors work shall satisfy all applicable local, state and federal codes applicable to their scope." },
    { title: "3. Progress Payments; Final Payment.", body: "3.1 General Contractor shall pay Subcontractor the Subcontractor Price for satisfactorily performing Subcontractor’s Work. Progress payments, less Retainage, shall be made to Subcontractor for Subcontractor’s Work performed, no more than 15 days after General Contractor receives from Owner payment for Subcontractor’s Work. General Contractor shall pay Subcontractor a final payment of the balance due no more than 15 days after General Contractor receives from Owner final payment for Subcontractor’s Work. All payments are subject to General Contractor’s receipt of such lien waivers, affidavits, warranties, guarantees, and other documentation required by this Subcontract, the Contract Documents, Exhibit B of this Subcontract Agreement or General Contractor.\n\n3.2 General Contractor may reject a payment application, or reject a previously approved payment application, in whole or in part, to protect General Contractor from loss or damage caused by Subcontractor’s failure to (A) timely perform the Subcontractor’s Work, (B) pay sub-subcontractors or suppliers, (C) promptly correct rejected, defective, or nonconforming Subcontractor’s Work, or (D) resolve third party claims or likely claims or supply General Contractor with sufficient security that the third party claims will be discharged. General Contractor may withhold 150% of the amount necessary to complete any portion of Subcontractor’s Work included on a punch list supplied by General Contractor, the Owner, or the Architect/Engineer.\n\n3.3 Application for final payment by Subcontractor shall constitute a waiver of claims by Subcontractor except those previously made in writing and identified by Subcontractor as unsettled." },
  ],
  [
    { title: "4. Time of Performance; Project Schedule; Schedule of Values.", body: "4.1 If requested by General Contractor, Subcontractor shall participate and cooperate in the development of the Project schedule and any revisions to the Project schedule. Subcontractor shall diligently and continuously prosecute and complete Subcontractor’s Work in accordance with the Project schedule, any revisions to the Project schedule, and any other scheduling requirements in this Subcontract. Subcontractor shall substantially complete the Subcontractor’s Work by the Date of Substantial Completion, and shall complete the Subcontractor’s Work by the Date of Final Completion. Subcontractors timely completion of work, shall be reflected in timeliness of payment. TIME IS OF THE ESSENCE OF THIS SUBCONTRACT.\n\n4.2 As a condition of payment, Subcontractor shall deliver to General Contractor a schedule of values satisfactory to General Contractor, allocating the total Subcontractor Price to the separate phases of Subcontractor’s Work, stating separately amounts for labor and materials and prorating overhead and profit among such separate phases." },
    { title: "5. Insurance.", body: "5.1 Prior to starting Subcontractor’s Work until the final acceptance of Subcontractor’s Work, Subcontractor shall maintain at its expense insurance that will protect it from all claims arising out of its operations under this Subcontract, whether the operations are by the Subcontractor, or any of its consultants or sub-subcontractors or anyone directly or indirectly employed by any of them, or by anyone for whose acts any of them may be liable. The insurance shall have policy limits at least as high as the Policy Limits (defined above), and shall be provided by an insurance company acceptable to General Contractor.\n\n5.2 Subcontractor shall maintain Completed Operations Liability Insurance for at least one year after the earlier of (A) 90 days following Substantial Completion of all the work under the Contract Documents, or (B) final payment to General Contractor.\n\n5.3 Subcontractor shall maintain at its own expense property and equipment insurance for the Subcontractor’s Work, including portions of the Subcontractor’s Work stored off-site or in transit.\n\n5.4 General Contractor and Subcontractor waive all rights against (A) each other and their officers, employees and agents, and (B) Owner, Architect/Engineer, Architect’s/Engineer’s consultants and their officers, employees and agents, for damages caused by any peril to the extent waived between General Contractor and the Owner and to the extent covered by property insurance provided under the Contract Documents or other property insurance applicable to the work, except such rights they may have to proceeds of insurance held by the Owner as fiduciary. Subcontractor shall require a similar waiver by its sub-subcontractors, agents, and employees. If the policies required by this section require an endorsement to provide for continued coverage where there is a waiver of subrogation, the owners of such policies shall cause them to be so endorsed.\n\n5.5 If Subcontractor fails to obtain and keep any of the insurance coverage required by this Subcontract, General Contractor may purchase such coverage and charge the expense to Subcontractor or terminate the Subcontract." },
  ],
  [
    { title: "6. Indemnity.", body: "6.1 Subcontractor is aware of the immunity it has from suits by its employees or third parties for damages relating to injuries suffered by its employees in the course of and arising out of their employment for the Subcontractor which may be brought outside of the workers’ compensation system. Subcontractor, for purposes of this Subcontract, waives that immunity and to the fullest extent permitted by law, Subcontractor shall indemnify, defend, and hold harmless General Contractor (including its owners, affiliates, subsidiaries, officers, directors, agents, shareholders, successors and employees), General Contractor’s other subcontractors, the Architect/Engineer, the Owner, and each of their agents, consultants, and employees (collectively, the “Indemnitees”) from and against all claims for bodily injury, property damage (including to the work itself), and all costs and expenses (including attorney fees), arising out of, or alleged to arise out of, the Subcontractor’s Work. Subcontractor, at Subcontractor’s sole expense, shall promptly dispose of all such indemnifiable claims, defend all lawsuits filed against General Contractor on any indemnifiable claim, pay all judgments rendered against General Contractor in such lawsuits, and reimburse General Contractor for all reasonable expenses incurred by General Contractor on the account of any indemnifiable claim, including attorney fees, expert witness fees and court costs. Subcontractor’s indemnity obligations apply regardless of whether the claim is caused or alleged to be caused by any joint or concurrent negligent act or omission by an Indemnitee, but Subcontractor is not required to indemnify for any claim proximately caused by the sole negligence or willful misconduct of General Contractor or General Contractor’s agents or contractors who are directly responsible to General Contractor, excluding Subcontractor. General Contractor may participate in the defense of any claims asserted against it, approve the selection of counsel, and approve the terms of any settlements made on its behalf.\n\n6.2 In any claim against any of the Indemnitees by any employee of Subcontractor or anyone for whose acts the Subcontractor may be liable, Subcontractor’s indemnification obligation is not limited in any way by any limitation on the amount or type of damages, compensation, or benefits payable by or for the Subcontractor under workers’ compensation acts, disability benefit acts, or other employee benefit acts." },
    { title: "8. Claims for Damages; Extensions of Time.", body: "8.1 Subcontractor shall give General Contractor written notice of all claims affecting or relating to the Subcontract Price for which the Owner is or may be liable under the Contract Documents no later than 3 business days after Subcontractor’s first observance of the facts giving rise to the claim, or, if sooner, within the time limits provided in the Contract Documents for like claims by General Contractor upon the Owner and in sufficient time for General Contractor to initiate such claims against the Owner in accordance with the Contract Documents. The claim shall proceed in the manner provided in the Contract Documents and Subcontractor shall be responsible for substantiating a claim submitted to the Owner on Subcontractor’s behalf. Subcontractor shall be responsible for all costs, expenses, and attorney fees incurred by it and by General Contractor relating to the claim.\n\n8.2 If Subcontractor is delayed, obstructed, hindered, or interfered with in a critical element of the Subcontractor’s Work by any cause beyond Subcontractor’s reasonable control and not due to the fault of Subcontractor, its officers, agents, employees, sub-subcontractors, or suppliers, then (A) Subcontractor shall be entitled to an extension of time for a period equivalent to the time lost by reason of such causes, but only if (1) Subcontractor gives General Contractor notice in writing of such delay, obstruction, hindrance, or interference within 3 business days of Subcontractor’s first observance of the facts giving rise thereto, (2) Subcontractor demonstrates that it could not have anticipated or avoided such delay, obstruction, hindrance, or interference and has used all available means to minimize the consequences thereof, and (3) Owner grants General Contractor an extension of time for the performance of Subcontractor’s Work; and (B) Subcontractor shall be entitled to an adjustment in the Subcontract Price to the extent provided in this Section.\n\n8.3 Subcontractor shall give General Contractor written notice of all claims affecting or relating to the Subcontractor’s Work not addressed above within 3 business days of Subcontractor’s first observance of the facts giving rise to the claim. All such claims shall be resolved in the manner provided in Section 16 (“Disputes & Settlements”).\n\n8.4 Subcontractor’s failure to assert a claim in the manner and within the time provided for in this Section constitutes a complete waiver of the claim." },
  ],
  [
    { title: "9. Work Changes.", body: "9.1 General Contractor may, without invalidating this Subcontract, order the Subcontractor in writing to make changes in the Subcontractor’s Work within the general scope of this Subcontract. The Subcontractor shall promptly commence such changed work and the Subcontractor’s Price, the Date of Final Completion, or both may be adjusted. No adjustment in the Subcontractor’s Price or the Date of Final Completion shall be made for any changes performed by the Subcontractor that have not been ordered by General Contractor, issued to Subcontractor in writing and signed by both parties. Subcontractor shall not deviate from the plans and specifications or substitute materials (including “or equal” materials) without the issuance of a written change order by General Contractor.\n\n9.2 If a change order is executed by General Contractor and Subcontractor, there shall be no subsequent adjustment based upon the effect or impact of the change contemplated by that change order, nor shall Subcontractor be entitled to any further time or compensation based upon the cumulative effect of multiple change orders.\n\n9.3 Additional information regarding Change Orders is included in Exhibit D, an attachment to this subcontract." },
    { title: "10. Clean-up and Protection of Work of Others.", body: "10.1 Subcontractor at all times shall keep the Construction Site free from rubbish, debris, and obstructions caused by its operations, and shall complete Subcontractor’s Work in such manner as to permit the next succeeding work to start without further cleaning. At the time of completion of Subcontractor’s Work in each area, Subcontractor shall leave the area “broom clean” and shall remove all of its tools, equipment, scaffolding, and surplus materials.\n\n10.2 Subcontractor shall not damage the work of others by its operations, and shall repair or pay the cost of repairing any such damage done by it.\n\n10.3 If after written notice to Subcontractor and if Subcontractor does not comply, General Contractor may perform any clean-up or repair work Subcontractor fails to perform promptly, in which case Subcontractor shall pay General Contractor the cost of the clean-up or repair work plus 10% for overhead and other indirect expenses." },
    { title: "11. Safety.", body: "11.1 Subcontractor shall perform the Subcontractor’s Work in a safe and reasonable manner. Subcontractor shall seek to avoid injury, loss, or damage to persons or property by taking reasonable steps to protect (A) employees and other persons at the construction site; (B) materials and equipment stored at the construction site or at off-site locations for use in performance of the work; and (C) all property and structures located at the construction site and adjacent to work areas, regardless of whether that property or structures are involved in the Subcontractor’s Work. Subcontractor shall establish its own safety program implementing safety measures, policies, and standards conforming to those required or recommended by governmental and quasi-governmental authorities having jurisdiction, or by General Contractor (Job Site Safety requirements are included in Exhibit C of this Subcontract Agreement), or by the Owner, including, but not limited to, requirements imposed by the Contract Documents.\n\n11.2 Subcontractor shall implement appropriate safety measures pertaining to the Subcontractor’s Work and the Project, including establishing safety rules, posting appropriate warnings and notices, erecting safety barriers, addressing full protection and establishing proper notice procedures to protect persons and property from injury, loss or damage.\n\n11.3 When use or storage of explosives or other hazardous materials or equipment or unusual methods are necessary for execution of the Subcontractor’s Work, the Subcontractor shall exercise utmost care and carry on such activities under supervision of properly qualified personnel. General Contractor shall not be responsible for materials and substances brought to the site by Subcontractor unless such materials or substances were required by the Contract Documents." },
  ],
  [
    { title: "12. Termination Without Fault of Subcontractor.", body: "If General Contractor or the Owner terminates the contract between them for any cause permitted by that contract (except a default by General Contractor), General Contractor by notice to Subcontractor may terminate this Subcontract. In addition, General Contractor may at any time and without cause by written notice to Subcontractor terminate this Subcontract and require Subcontractor to cease the Subcontractor’s Work. In either event, Subcontractor, as directed by General Contractor, shall discontinue Subcontractor’s Work, remove its equipment, materials, and employees from the Construction Site, and take such action as necessary to terminate its agreements with its sub-subcontractors and suppliers, and to minimize its losses resulting from such termination. Subcontractor shall then promptly deliver to General Contractor a statement covering the balance owed under this Subcontract for work completed prior to the termination, and for additional costs for which it is liable by reason of such termination. This statement shall be the maximum amount for which General Contractor may be liable by virtue of its termination of the Subcontract. Subcontractor is not entitled to profit or overhead on unperformed Work." },
    { title: "13. Termination Upon Default of Subcontractor.", body: "If Subcontractor defaults on any term of this Subcontract or the Contract Documents, General Contractor may issue a notice giving the Subcontractor two days (48 Hour Notice) to correct the default. If Subcontractor fails to correct the default within the two-day period, General Contractor may, without waiving any rights or remedies it has, take whatever steps it deems necessary or appropriate to correct any deficiencies at the cost of Subcontractor, which will be liable for that cost plus General Contractor’s reasonable overhead, profit, and attorney fees. In addition to correcting Subcontractor’s default upon the expiration of the two-day period, General Contractor may issue a second notice of default giving the Subcontractor four days (96 Hour Notice) to correct the default. If Subcontractor fails to correct the default within that four-day period, General Contractor may terminate the Subcontract, and all costs associated with completing the Subcontractor’s Work, including reasonable overhead, profit, and attorney fees, will be deducted from any amounts owed to Subcontractor. Subcontractor is liable for any amount by which the cost of completing the Subcontractor’s Work (including reasonable overhead, profit, and attorney fees) exceeds any amounts owed or to be owed to Subcontractor." },
    { title: "14. Warranties; Correction of Work.", body: "14.1 Subcontractor warrants and guarantees that all materials and equipment furnished under this Subcontract shall be new unless otherwise specified, and that all of Subcontractor’s Work will be of first quality, free from faults or defects in materials or workmanship, and in strict accordance with requirements of this Subcontract and the Contract Documents. All work not conforming to these requirements, including substitutions not properly approved and authorized, shall be considered defective. Subcontractor’s warranties under this Subcontract must extend at least as long as General Contractor’s warranties under the Contract Documents, but in any event no less than one year from the date of Subcontractor’s last work.\n\n14.2 Subcontractor shall promptly correct at its cost all of Subcontractor’s Work rejected as defective or as failing to conform to the requirements of this Subcontract or the Contract Documents whether observed before or after substantial completion of the Project and whether or not fabricated, installed, or completed." },
  ],
  [
    { title: "15. Liquidated and Consequential Damages.", body: "15.1 General Contractor shall assess liquidated damages against Subcontractor in proportion to the Subcontractor’s share of the responsibility for the delay on the project schedule. Liquidated damages are specified in the Definitions Section, Item P, of this subcontract agreement. This section does not limit Subcontractor’s liability to General Contractor for General Contractor’s actual delay damages caused by Subcontractor’s delay.\n\n15.2 Subcontractor waives all claims against General Contractor for consequential damages arising out of or relating to this Subcontract, including damages for principal office expenses (which includes unabsorbed principal office expenses) and the compensation of personnel stationed there; for loss of financing, business and reputation; and for loss of profit." },
    { title: "16. Disputes and Settlement.", body: "16.1 All claims, except for those governed by Sections 8.1 or 8.2 and those that have been waived under other terms of this Subcontract, shall be subject to arbitration using the Commercial Construction Industry Rules of the American Arbitration Association, and the hearing shall occur in the county where the Project is located unless the parties agree otherwise.\n\n16.3 To the extent claims between General Contractor and Subcontractor involve in whole or in part claims between the Owner and General Contractor, claims between General Contractor and Subcontractor shall be, at the General Contractor’s election, decided by the same tribunal and in the same forum as claims between the Owner and General Contractor. If the provisions for resolution of claims between the Owner and General Contractor contained in the Contract Documents do not permit consolidation or joinder with claims of third parties such as Subcontractor, resolution of claims between General Contractor and Subcontractor involving in whole or in part claims between the Owner and General Contractor may be stayed, at the General Contractor’s sole option, pending conclusion of any claim resolution proceeding between the Owner and General Contractor.\n\n16.4 Subcontractor shall continue the Subcontractor’s Work and maintain the Project schedule during any dispute resolution proceedings.\n\n16.5 Subcontractor hereby waives (to the extent permitted by applicable law) any right it may have to a trial by jury of any claim.\n\n16.6 The costs and attorney fees of any binding dispute resolution procedure (whether arbitration or litigation) shall be paid by the non-prevailing party." },
    { title: "17. Assignment; Subcontracting; Work for Others on the Project.", body: "Subcontractor shall not assign this Subcontract or any right or liability relating to it, or subcontract any part of the Subcontractor’s Work, without the General Contractor’s written consent. Subcontractor shall not, without General Contractor’s express written consent, provide any goods or services for the Project to Owner or any other contractor or subcontractor other than to General Contractor." },
    { title: "18. Divisibility.", body: "If any provision of this Subcontract is held by a court or arbitrator of competent jurisdiction invalid or unenforceable, such provision shall be ineffective only to that extent without invalidating or rendering unenforceable any other provision of this Subcontract." },
    { title: "19. Applicable Law.", body: "This Subcontract shall be construed in accordance with and governed by the internal substantive law of the Commonwealth of Kentucky regardless of the laws that might otherwise govern under principles of conflict of laws." },
    { title: "20. Non-waiver.", body: "The waiver by either party of any breach of any provision of this Subcontract does not constitute a waiver of any other breach of any provision of this Subcontract. No payment of the Subcontract Price, whether a partial payment or the final payment, shall be deemed an acceptance of Subcontractor’s Work covered thereby." },
    { title: "21. Entire Agreement.", body: "This Subcontract constitutes the entire agreement between the parties and supersedes all prior or contemporaneous written or oral agreements between the parties with respect to the subject matter of this Subcontract. This Subcontract may not be amended or modified except by a written change order duly executed by the parties hereto." },
    { title: "22. Manner of Acceptance.", body: "This Subcontract will be deemed effective upon the earlier of the Subcontractor’s signature below or the Subcontractor’s acceptance as provided in this Section. By shipping goods, by acknowledging receipt of this Subcontract, or by commencing the Subcontractor’s Work, Subcontractor agrees to the terms and conditions contained in this Subcontract, although its agreement to such terms and conditions is not limited to the foregoing methods. This Subcontract may be accepted by Subcontractor without signature." },
  ],
];

function clauseParagraphs(clause: Clause, start = 0, end?: number, showTitle = true): Clause {
  return {
    title: showTitle ? clause.title : "",
    body: clause.body.split("\n\n").slice(start, end).join("\n\n"),
  };
}

const fullAgreement = agreementPages.flat();
const previewAgreementPages: Clause[][] = [
  [fullAgreement[1], fullAgreement[2], fullAgreement[3], clauseParagraphs(fullAgreement[4], 0, 2)],
  [clauseParagraphs(fullAgreement[4], 2, undefined, false), fullAgreement[5], clauseParagraphs(fullAgreement[6], 0, 2)],
  [clauseParagraphs(fullAgreement[6], 2, undefined, false), fullAgreement[7], fullAgreement[8], fullAgreement[9]],
  [fullAgreement[10], fullAgreement[11], fullAgreement[12], fullAgreement[13], clauseParagraphs(fullAgreement[14], 0, 2)],
  [clauseParagraphs(fullAgreement[14], 2, undefined, false), ...fullAgreement.slice(15)],
];

const invoiceGuidelines = [
  "All subcontractors should have a subcontract agreement with Mefford Contracting in place prior to starting work on one of our projects. This is to avoid contract price, scope of work and other legal issues that could arise after work has begun. If you are requested to start and you have not received a subcontract agreement yet, please notify your site superintendent or project manager.",
  "Exhibit A, B, C and D are mandatory additions to the subcontract agreement with Mefford Contracting. If you have received a subcontract agreement that does not include these exhibits, please make the site superintendent and/or project manager aware so they can have these exhibits prepared for you. Signing these is required before payment can be made.",
  "When submitting an invoice for payment, a subcontractor’s conditional lien waiver shall be submitted at the same time. A W9 and up to date Certificate of Insurance is also required. Not receiving this required paperwork will hold up processing and signing of your check until we have received it.",
  "All invoices should be received by the 5th of the month. (February invoices shall be received by the 5th of March). Mefford Contracting invoices shall be submitted to Owner by the 15th of the following month (March 5th Subcontractor Invoices shall be billed to Owner on March 15th or earlier). If a subcontractor invoice is not received by the 5th of the month, we cannot guarantee that it will get to the Owner on the associated Owner invoice.",
  "All Owners pay on different schedules and this is usually tied to the contract agreement for the project. All subcontractors shall assume that payment can take up to 60 days from the time of Mefford Contracting’s invoice to the Owner (March 15th invoice could take up to May 15th to be paid).",
  "If a subcontractor is not able to wait for the Owner’s to pay an invoice prior to receiving their payment, please contact your Project Manager. Do not assume that any quick payment option has been agreed upon unless written approval has been given.",
  "All submitted invoices shall be reviewed by the site superintendent and/or project manager prior to being approved for full billing on the Owner’s invoice. Please do not try to overbill according to your percentage of work complete and/or your stored materials on/off site. Any discrepancies found will be communicated as promptly as possible, but this could result in underbilling your invoice or omission of your invoice entirely from the Owner’s invoice. At times, Mefford Contracting may request a larger bill due to project or subcontractor requirements, but do not assume this is the standard process for invoicing.",
  "All invoices shall be submitted to invoices@meffcon.com or by mail to 109 Fieldview Dr. Versailles, KY 40383. Do not hand deliver or email invoices to the site superintendent, hand deliver to one of our office locations or email to a partner as these get lost in normal business activities. This email address (invoices@meffcon.com) has been setup specifically to receive your monthly invoices only.",
  "All subcontractors shall have 10% (or contract specific percentages) withheld from payment for retainage. Once a project is complete and Owner’s have released retainage, a separate and final retainage check shall be issued.",
  "All payments to subcontractors shall be mailed out within 15 days of owner’s cleared payment. Do not request a direct deposit, payment with credit card or any other form of reimbursement as we cannot accommodate at this time.",
  "Lastly, unless an agreement is discussed prior to invoicing, wait for your check to show up in the mail. Please do not show up looking for payment as bookkeeping and/or your site superintendent will not have the ability to sign or print a check for you on the spot. Please instead, contact your Project Manager.",
];

const safetyGuidelines = [
  "ACCIDENTS OR INJURIES, no matter how minor, shall be reported to your Supervisor for immediate attention.",
  "GOOD HOUSEKEEPING shall be practiced at all construction projects.",
  "STORAGE AREAS, AISLES AND WALKWAYS shall be kept clean and all materials shall be neatly piled and stacked.",
  "MATERIAL, EQUIPMENT, LUMBER, etc. also shall be secured where it is liable to be blown from a roof or high place during a wind storm.",
  "SUPERINTENDENT OR FOREMAN will enforce safety rules.",
  "FOR YOUR PROTECTION report all unsafe conditions and unsafe acts to your supervisor.",
  "HORSEPLAY OR PRACTICAL JOKES by any individual is hazardous and will not be permitted on job site. Violators will be subject to disciplinary action.",
  "ALL POSTED safety rules and warning signs shall be obeyed.",
  "THE USE, SALE OR POSSESSION OF ALCOHOL AND OTHER DRUGS are prohibited on the job.",
  "RIDING OF EQUIPMENT PROHIBITED. No person shall ride any hook, hoist or other material handling equipment.",
  "HARD HATS shall be worn by all personnel at all times and will be non-conductive.",
  "EYE AND FACE PROTECTIVE EQUIPMENT which is required and made available shall be worn when the nature of the operation presents a potential eye or face injury.",
  "WEAR ASSIGNED HEARING PROTECTION when performing loud operations such as jackhammering.",
  "SHOES shall be first grade, steel toed, hard soled and ankle high.",
  "GLOVES shall be worn when handling rough edges or abrasive materials.",
  "WEAR ASSIGNED RESPIRATORS when working in areas containing toxic gases, vapors, fumes, dusts or mists.",
  "CLOTHING shall consist of long pants and shirts with sleeves. All persons on site shall wear high visibility shirts and/or high visibility vests at all times.",
  "PROTECTION FROM FALLING OBJECTS shall be provided by strong materials according to standards.",
  "EXCAVATION AND TRENCHING shall, where more than 5 feet in depth, be shored, braced or sloped to an angle of repose consistent with the material being excavated.",
  "HAND TOOLS shall be kept in safe conditions and shall not be used for other than their intended use.",
  "MACHINERY WHEN OPERATING shall not be oiled, cleaned, adjusted or refueled.",
  "VISUALLY INSPECT all tools, ladders and scaffolds and equipment for defects before each use.",
  "LADDERS shall be according to approved standards and used as directed.",
  "INSPECT ALL rigging and slings daily.",
  "POWDER ACTUATED TOOLS shall be used only by delegated persons who have been instructed and trained in their safe use.",
  "POWER TOOLS shall be operated only by trained authorized personnel, with guards furnished by the manufacturer “in place,” and if electrical, shall be grounded or double insulated.",
  "SALMANDERS AND TEMPORARY HEATERS: Sufficient ventilation shall be maintained when temporary heating devices are used.",
  "ELECTRICAL CORDS shall be placed in a safe location, protected from physical damage and be of the 3 wire type. All 15 and 20 amp circuits not part of permanent wiring shall be protected by GFCI’s or Assured Grounding Program. Extension cords shall not be fastened with staples, hung from nails, or suspended from wires.",
  "WELDING AND BURNING OPERATIONS shall be conducted only by authorized personnel under proper supervision. Approved personal protective equipment, including fire extinguishers, shall be provided and used.",
  "COMPRESSED GAS CYLINDERS shall be chained or properly secured in an upright position, and shall be placed in cylinder carts whenever being transported to different locations on the project. Cylinders shall be kept at a safe distance or shielded from welding/cutting operations. Cylinders shall not be placed where they can contact an electrical circuit.",
  "SOURCES OF IGNITION shall be prohibited in areas where flammable liquids or explosives are stored or issued, and appropriate warning signs shall be posted at these locations.",
  "APPROVED SAFETY CANS shall be used when transporting and storing flammable liquids. Stored liquids shall be clearly marked and readable.",
  "KNOW THE LOCATION and proper use techniques for all firefighting equipment.",
  "KEEP ONLY the minimum amount of tools and equipment needed on scaffolds. Do not let debris and unneeded tools and materials accumulate.",
  "SCAFFOLDS AND PLATFORMS shall be constructed of lumber or metal in accordance with safety standards. Any work above 6’ shall have fall protection in place.",
  "WEAR FULL BODY HARNESS and life lines when there is a danger of a fall and safety net or perimeter protection is not installed.",
  "EDGES OF BUILDINGS AND STRUCTURES shall be provided with guardrails and toe boards on all floors according to standards. The protective barriers shall not be removed except as directed by the supervisor.",
  "FLOOR AND ROOF OPENINGS shall be planked over or barricaded by guardrails and toe boards.",
  "TEMPORARY STAIRS shall be provided whenever practical, except in all cases where construction has progressed to a height in excess of 60 inches above grade. They shall be equipped with handrails.",
  "ASBESTOS IS A COMMON HAZARD during demolition, remodeling and repair operations. If you contact any material that may be asbestos, notify your supervisor immediately.",
  "DO NOT USE ANY CHEMICALS or enter any area where they are being used unless you fully understand any health hazards associated with them and are equipped with proper protective equipment. Read carefully all manufacturer’s instructions and warnings.",
  "WHEN WORKING IN EXISTING PLANT or institutional facilities, follow all of their safety requirements to the letter. The violation of a customer’s safety rules will result in the same disciplinary action as the violation of your own company’s rules.",
  "KNOW THE LOCATION OF FIRST AID SUPPLIES, telephones and emergency phone numbers.",
  "LIFT CAREFULLY: If the load is bulky or too heavy, get help. Do not carry objects in a way that obstructs your vision. Remember to bend in lifting an object and to lift with the legs, not the back.",
  "BE ALERT: Watch for hazards and correct them before they become accidents. Learn the safe way to do your job before you start. If you are not sure you thoroughly understand the job, ask your foreman for additional instructions.",
];

const changeOrderGuidelines = [
  "NO WORK IS TO BE DONE UNTIL A SIGNED CHANGE ORDER IS IN PLACE BETWEEN GENERAL CONTRACTOR AND SUBCONTRACTOR",
  "All Subcontractor requests for Change Orders shall be sent to the Mefford Contracting Project Manager",
  "Email correspondence IS NOT a written Change Order, nor can Email Confirmation be given as an Approval to commence work on a Change Order",
  "Approved Change Order documentation shall originate from General Contractor at all times",
  "All Change Orders shall reflect adjustment time to project schedule",
  "No Subcontractor Change Orders shall be issued to the Owner directly",
  "Change Order pricing shall not be discussed with Owner directly at any time",
];

function money(value: string) {
  return `$${Number(value || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

function ContractHeader({ exhibit, title }: { exhibit?: string; title?: string }) {
  return <header className="contract-page-header"><strong>MEFFORD CONTRACTING, LLC</strong><b>{exhibit || "SUBCONTRACT AGREEMENT"}</b>{title ? <em>{title}</em> : null}</header>;
}

function DigitalSignatureLine({ label, compact = false }: { label: string; compact?: boolean }) {
  const [selected, setSelected] = useState(false);
  return <button type="button" className={`digital-signature-line${compact ? " compact" : ""}${selected ? " selected" : ""}`} aria-pressed={selected} aria-label={`${label || "Signature"} Digital Signature Field`} onClick={() => setSelected((current) => !current)}><span>{label}</span><b>{selected ? "Ready For Digital Signature" : ""}</b><i>{selected ? "✓ Digital Field Selected" : "Select Digital Field"}</i></button>;
}

function ContractFooter({ page, total = 12 }: { page: number; total?: number }) {
  return <footer className="contract-page-footer" aria-label={`Page ${page} Of ${total}`}><DigitalSignatureLine label="Subcontractor Initial:" compact /></footer>;
}

function Acknowledgement({ subcontractor, signerName }: { subcontractor: string; signerName: string }) {
  return <div className="contract-acknowledgement"><div><span>Company</span><strong>{subcontractor}</strong></div><div><span>Authorized Signer</span><strong>{signerName || "Pending"}</strong></div><div className="acknowledgement-signature"><DigitalSignatureLine label="Signature" /></div><div><span>Date</span><strong>Automatic At Signing</strong></div></div>;
}

function ClausePage({ page, clauses }: { page: number; clauses: Clause[] }) {
  return <article className="contract-sheet" data-page={page}><div className="contract-page-body agreement-copy">{clauses.map((clause, clauseIndex) => <section key={`${clause.title}-${clauseIndex}`}>{clause.title ? <h3>{clause.title}</h3> : null}{clause.body.split("\n\n").map((paragraph) => <p key={paragraph.slice(0,80)}>{paragraph}</p>)}</section>)}</div><ContractFooter page={page} /></article>;
}

export function FullSubcontractPreview(props: PreviewProps) {
  const definitions = [
    ["A.", "Owner", props.ownerName],
    ["B.", "General Contractor", "Mefford Contracting, LLC"],
    ["C.", "Subcontractor", props.subcontractor],
    ["D.", "Contract", `The contract between Owner and Contractor dated: ${props.ownerContractDate}`],
    ["E.", "Project", `${props.projectName} · Project #${props.projectNumber}`],
    ["F.", "Construction Site", props.constructionSite],
    ["G.", "Architect/Engineer", props.architect || "N/A"],
    ["H.", "Contract Documents", "The Contract; all general, special, and supplemental conditions, drawings, plans, and specifications referred to in, and made part of, the Contract; all addenda and exhibits to the Contract; and all other documents forming a part of the Contract."],
    ["I.", "Subcontractor’s Work", "As specified in Exhibit A of this Subcontract Agreement"],
    ["J.", "Subcontractor Price", money(props.price)],
    ["K.", "Retainage", `${props.retainage}%`],
    ["L.", "Date of Substantial Completion", `The date on which the Subcontractor’s Work is sufficiently complete such that it can be used for its intended purpose, which shall occur no later than: ${props.substantialDate}`],
    ["M.", "Date of Final Completion", props.finalDate],
    ["N.", "Policy Limits", `Commercial General Liability: ${money(props.cglLimit)} · Worker’s Compensation: ${money(props.workersCompLimit)}`],
    ["O.", "Effective Date", "The date of the Subcontractor’s acceptance of this Subcontract under Section 23."],
    ["P.", "Liquidated Damages", props.liquidatedDamages],
  ];

  return <section className="pdf-preview full-contract-preview" role="dialog" aria-modal="true" aria-labelledby="full-contract-title">
    <div className="pdf-toolbar full-contract-toolbar"><div><span className="pdf-ready">PDF</span><span><strong id="full-contract-title">SC-009 · Complete Subcontract Preview</strong><small>12-Page Agreement · Draft Prepared {props.subcontractDate} · All Current Answers Applied</small></span></div><div><span className="page-count-pill">12 Pages + Proposal</span><button className="secondary-action" onClick={props.onClose}>Close</button><button className="primary-action" onClick={() => window.print()}>Print / Save As PDF</button></div></div>
    <nav className="contract-preview-nav" aria-label="Contract Preview Pages"><span>Complete Packet</span>{Array.from({ length: 12 }, (_, index) => <a href={`#contract-page-${index + 1}`} key={index}>Page {index + 1}</a>)}<a href="#contract-proposal">Proposal</a></nav>
    <div className="contract-pages">
      <article className="contract-sheet" id="contract-page-1" data-page="1"><ContractHeader /><div className="contract-page-body"><h2>DEFINITIONS</h2><table className="contract-definitions"><tbody>{definitions.map((row) => <tr key={row[0]}><td>{row[0]}</td><th>{row[1]}:</th><td>{row[2]}</td></tr>)}</tbody></table><h2>BACKGROUND</h2><p>This Subcontract is effective as of the Effective Date between General Contractor and Subcontractor under the following circumstances:</p><p>A. Under the Contract between General Contractor and Owner, General Contractor has agreed to provide certain work, services, materials, equipment, tools, labor and supervision for the Project at the Construction Site.</p><p>B. Subcontractor has agreed to perform a portion of the work under the Contract Documents for General Contractor, subject to the terms and conditions set forth in this Subcontract.</p><h2>AGREEMENT</h2><section className="agreement-copy first-agreement-clause"><h3>{fullAgreement[0].title}</h3>{fullAgreement[0].body.split("\n\n").map((paragraph) => <p key={paragraph.slice(0,80)}>{paragraph}</p>)}</section></div><ContractFooter page={1} /></article>
      {previewAgreementPages.map((clauses, index) => <div id={`contract-page-${index + 2}`} key={index}><ClausePage page={index + 2} clauses={clauses} /></div>)}
      <article className="contract-sheet" id="contract-page-7" data-page="7"><ContractHeader /><div className="contract-page-body signature-contract-page"><h2>23. Signature/Date</h2><div className="signature-columns"><section><h3>SUBCONTRACTOR:</h3><strong>{props.subcontractor}</strong><DigitalSignatureLine label="Signature:" /><p>By: <span>{props.signerName || "Pending"}</span></p><p>Name: <span>{props.signerName || "Pending"}</span></p><p>Title: <span>{props.signerTitle || "Pending"}</span></p><p>Date: <span>Automatic At Signing</span></p><small>Signing Email: {props.signerEmail || "Not Entered"}</small></section><section><h3>GENERAL CONTRACTOR:</h3><strong>MEFFORD CONTRACTING LLC, a Kentucky limited liability company</strong><DigitalSignatureLine label="Signature:" /><p>Name: <span>Assigned Mefford Signer</span></p><p>Title: <span>Assigned At Distribution</span></p><p>Date: <span>Automatic At Signing</span></p></section></div></div><ContractFooter page={7} /></article>
      <article className="contract-sheet" id="contract-page-8" data-page="8"><ContractHeader exhibit="SUBCONTRACT AGREEMENT" title="EXHIBIT A" /><div className="contract-page-body exhibit-a-copy"><dl><div><dt>Subcontractor:</dt><dd>{props.subcontractor}</dd></div><div><dt>Project:</dt><dd>{props.projectName}</dd></div><div><dt>Subcontractor Price:</dt><dd>{money(props.price)}</dd></div><div><dt>Effective Date:</dt><dd>Established At Signature</dd></div></dl><p>The below states the subcontractor’s work, which is defined for the above Project for Mefford Contracting, LLC. Definitions below in no way limit the subcontractor from completion of any and all items specific to their trade in the contract documents, plans and/or specifications, any items added to subcontractor’s scope of work by issuance of a change order or any items administratively omitted within this scope of work that would generally be accepted as industry standard for the subcontractor’s trade. Subcontractors work shall satisfy all applicable local, state and federal codes applicable to their scope</p><section><h3>Scope of Work</h3><p>{props.scope}</p></section><section><h3>Subcontractor Proposal Attachment</h3><p>{props.proposalName || "No Proposal Attached"}</p><small>The uploaded proposal is appended after the twelve-page agreement.</small></section></div><ContractFooter page={8} /></article>
      <article className="contract-sheet" id="contract-page-9" data-page="9"><ContractHeader exhibit="EXHIBIT B" title="PROCESS FOR INVOICING AND RECEIVING PAYMENT" /><div className="contract-page-body exhibit-copy"><p>Mefford Contracting, LLC strives to process and pay subcontractor invoices in a timely manner. That being said, subcontractor assistance is required to make sure all paperwork is in our possession before checks are mailed out. Below are the guidelines for subcontractor invoicing and payment to try and be as transparent as possible.</p><ol>{invoiceGuidelines.map((item) => <li key={item.slice(0,70)}>{item}</li>)}</ol><p>If you have any questions, please call or email concerning any payment issues. We look forward to working with you and hope this transparency assists in expediting your invoice payments. Please sign below that you accept these terms. Thank you.</p><Acknowledgement subcontractor={props.subcontractor} signerName={props.signerName} /></div><ContractFooter page={9} /></article>
      <article className="contract-sheet" id="contract-page-10" data-page="10"><ContractHeader exhibit="EXHIBIT C" title="GENERAL SAFETY REQUIREMENTS ON ALL PROJECTS" /><div className="contract-page-body exhibit-copy safety-copy"><p>Safety and the well-being of its employees, subcontractors and material suppliers is of the upmost importance to Mefford Contracting. The following shall be followed on all projects for Mefford Contracting and shall be signed off on by an authorized subcontractor company representative prior to work being performed on our site.</p><ol>{safetyGuidelines.slice(0,29).map((item) => <li key={item.slice(0,70)}>{item}</li>)}</ol></div><ContractFooter page={10} /></article>
      <article className="contract-sheet" id="contract-page-11" data-page="11"><ContractHeader exhibit="EXHIBIT C · CONTINUED" title="GENERAL SAFETY REQUIREMENTS ON ALL PROJECTS" /><div className="contract-page-body exhibit-copy safety-copy"><ol start={30}>{safetyGuidelines.slice(29).map((item) => <li key={item.slice(0,70)}>{item}</li>)}</ol><p>As an authorized representative of {props.subcontractor}, I have read and fully understand the above safety guidelines for all Mefford Contracting projects. Shall an employee of my company not uphold the safety guidelines and expectations as set forth by Mefford Contracting, Mefford Contracting shall have the right to have said employee removed from site. Their return to site shall only occur upon Mefford Contracting’s approval.</p><Acknowledgement subcontractor={props.subcontractor} signerName={props.signerName} /></div><ContractFooter page={11} /></article>
      <article className="contract-sheet" id="contract-page-12" data-page="12"><ContractHeader exhibit="EXHIBIT D" title="CHANGE ORDERS GUIDELINES" /><div className="contract-page-body exhibit-copy change-order-copy"><p>Change Orders are a common occurrence in all aspects of construction. At Mefford Contracting, we understand the need for change orders and want to assist Subcontractors in making sure they are paid appropriately for work being performed. With that said, the following requirements shall be upheld at all times regarding change orders to protect the Owner, the General Contractor and all Subcontractors.</p><ul>{changeOrderGuidelines.map((item) => <li key={item}>{item}</li>)}</ul><p>As an authorized representative of {props.subcontractor}, I have read and fully understand the above change order guidelines for all Mefford Contracting projects. Shall an employee of my company perform change order work without following the guidelines as set forth by Mefford Contracting, Mefford Contracting, nor the Owner, shall not be responsible for financial and schedule ramifications incurred by Subcontractor.</p><Acknowledgement subcontractor={props.subcontractor} signerName={props.signerName} /></div><ContractFooter page={12} /></article>
      <article className="contract-sheet proposal-sheet" id="contract-proposal"><ContractHeader exhibit="EXHIBIT A ATTACHMENT" title="SUBCONTRACTOR PROPOSAL" /><div className="contract-page-body"><span className="proposal-file-mark">PDF</span><h2>{props.proposalName || "No Proposal Attached"}</h2><p>This attachment will be appended in full after the subcontract agreement when the final signature packet is generated.</p><div className="proposal-verification"><span>✓ Filename Confirmed</span><span>✓ Assigned To Exhibit A</span><span>✓ Included In Signature Packet</span></div><small>Prototype note: upload a real proposal to include its pages in the production PDF assembly service.</small></div><footer className="contract-page-footer"><span>Exhibit A Proposal Attachment</span><span>Following Page 12</span></footer></article>
    </div>
  </section>;
}
