export const QUALITY_INSPECTION_RECORD_TYPE = "Quality Inspections";
export const QUALITY_ITEM_RECORD_TYPE = "Quality Items";

export type QualityQuestion = {
  id: string;
  group: string;
  label: string;
  input: "check" | "text" | "choice";
  choices?: string[];
  required: boolean;
};

export type QualityTemplate = {
  id: string;
  title: string;
  shortTitle: string;
  sourceDocument: string;
  timing: string;
  questions: QualityQuestion[];
};

export type ScheduleQualityCategory = {
  id: string;
  label: string;
  templateId: string;
  leadDays: number;
};

const check = (id: string, group: string, label: string): QualityQuestion => ({ id, group, label, input: "check", required: true });
const text = (id: string, group: string, label: string): QualityQuestion => ({ id, group, label, input: "text", required: true });
const choice = (id: string, group: string, label: string, choices: string[]): QualityQuestion => ({ id, group, label, input: "choice", choices, required: true });

const standard = (prefix: string): QualityQuestion[] => [
  check(`${prefix}-site-safety`, "Planning & Safety", "Site coordination and safety concerns have been addressed."),
  check(`${prefix}-submittals`, "Planning & Safety", "Required submittals are complete, approved, and returned."),
  check(`${prefix}-delivery`, "Logistics", "Material delivery dates and off-loading responsibilities are established."),
  check(`${prefix}-storage`, "Logistics", "Material staging, storage, and protection are established."),
  check(`${prefix}-coordination`, "Coordination", "Coordination with affected trades and activities is complete."),
  check(`${prefix}-scope`, "Coordination", "The subcontractor's complete scope of work is defined."),
];

const closeout = (prefix: string): QualityQuestion[] => [
  check(`${prefix}-nonroutine`, "Completion", "Non-routine tasks and special conditions have been identified."),
  check(`${prefix}-testing`, "Completion", "Required inspections and testing have been identified and scheduled."),
  check(`${prefix}-cleanup`, "Completion", "Cleanup and protection responsibilities are established."),
];

export const PREWORK_QUALITY_TEMPLATES: QualityTemplate[] = [
  {
    id: "above-ceiling",
    title: "Pre-Above Ceiling Meeting",
    shortTitle: "Above Ceiling",
    sourceDocument: "Pre-Above Ceiling Meeting.pdf",
    timing: "Before ceiling closure and again after any unsatisfactory attempt",
    questions: [
      ...standard("ac"),
      check("ac-grid", "Layout", "Ceiling grid layout has been coordinated."),
      check("ac-soffits", "Layout", "Soffit and bulkhead locations have been coordinated."),
      check("ac-heights", "Layout", "Finished ceiling heights are confirmed."),
      check("ac-firestop", "Life Safety", "Fire stopping and draft stopping are complete and visible for inspection."),
      check("ac-special-layout", "Coordination", "Lights, diffusers, and other specialty ceiling devices are laid out."),
      check("ac-screens", "Coordination", "Projector screens and their required clearances are coordinated."),
      check("ac-grid-label", "Identification", "Required ceiling-grid labeling is complete."),
      check("ac-insulation", "Insulation", "Building and pipe insulation requirements are complete."),
      check("ac-support", "Support", "Wiring and light fixtures have independent compliant support."),
      check("ac-access", "Access", "Access doors have the required operating and service clearance."),
      check("ac-old-wire", "Existing Conditions", "Abandoned wiring has been removed from the deck."),
      check("ac-deck-anchor", "Support", "All remaining wiring is anchored to the deck."),
      check("ac-heat-detectors", "Life Safety", "Temporary heat detectors are installed where required."),
      check("ac-inspection", "Inspection", "Required above-ceiling inspections have occurred."),
      check("ac-jboxes", "Identification", "Junction boxes are covered and labeled."),
      check("ac-pipe-duct", "Identification", "Pipe and duct systems are labeled."),
      check("ac-dimensions", "Layout", "Critical dimensions have been field verified."),
      ...closeout("ac"),
    ],
  },
  {
    id: "concrete",
    title: "Pre-Concrete Meeting",
    shortTitle: "Concrete",
    sourceDocument: "Pre-Concrete Meeting.pdf",
    timing: "Before every placement or pour sequence and after any unsatisfactory attempt",
    questions: [
      check("co-site-safety", "Planning & Safety", "Site coordination and safety concerns have been addressed."),
      check("co-submittals", "Planning & Safety", "Concrete submittals and mix designs are approved and returned."),
      check("co-mix", "Material", "The correct concrete mix design and strength are confirmed."),
      check("co-water", "Material", "Water-cement ratio and any site-added water limitations are confirmed."),
      check("co-aggregate", "Material", "Aggregate size is confirmed."),
      check("co-weather", "Placement", "Temperature and weather are appropriate for placement."),
      choice("co-placement", "Placement", "Placement method is confirmed.", ["Pump Truck", "Grout Truck", "Wheelbarrow", "Direct Chute", "Other / Not Applicable"]),
      check("co-overhead", "Safety", "Overhead power-line hazards are controlled."),
      check("co-washout", "Environmental", "Concrete washout location is established."),
      check("co-trades", "Coordination", "Affected trades and activities are coordinated."),
      check("co-underground", "Inspection", "Underground plumbing and electrical inspections are complete."),
      check("co-bud", "Existing Conditions", "BUD/811 locating is complete for footer excavation."),
      check("co-sleeves", "Coordination", "All required penetrations and sleeves are installed."),
      choice("co-finish", "Finish", "Concrete finish is confirmed.", ["Broom", "Smooth", "Picture Frame", "Exposed / Architectural", "Other"]),
      check("co-blankets", "Curing", "Concrete blankets are available where required."),
      check("co-decorative", "Finish", "Stamp, stain, pattern, and sample requirements are confirmed."),
      check("co-pull-forms", "Finish", "Forms that must be removed for exposed finishing are identified."),
      check("co-slope", "Layout", "Required slab and paving slopes are confirmed."),
      check("co-elevation", "Layout", "Correct elevation has been field verified."),
      check("co-measurements", "Layout", "All pre-pour dimensions have been field checked."),
      check("co-location", "Layout", "Pour boundaries and location match the current drawings."),
      check("co-vapor", "Assembly", "Required vapor barrier is installed and undamaged."),
      check("co-insulation", "Assembly", "Required under-slab insulation is installed."),
      check("co-expansion", "Assembly", "Expansion material and isolation joints are installed."),
      check("co-control", "Joints", "Control-joint locations and timing are confirmed."),
      check("co-reinforcement", "Reinforcement", "Reinforcement, embeds, chairs, size, and locations are correct."),
      check("co-curing", "Curing", "Curing method and responsible party are confirmed."),
      check("co-ada", "Accessibility", "ADA slopes, landings, and clearances are confirmed."),
      check("co-subgrade", "Subgrade", "Rock subgrade thickness, elevation, and compaction are verified."),
      check("co-photos", "Evidence", "Pre-pour photographs have been captured."),
      check("co-brick-ledge", "Layout", "Brick-ledge dimensions and elevations are correct."),
      check("co-sidewalk-utilities", "Coordination", "Utilities are installed before sidewalk placement."),
      check("co-ramp-treads", "Accessibility", "Required ramp tread or detectable-warning details are confirmed."),
      check("co-cure-weather", "Curing", "Forecast conditions support the full three-to-five-day curing period."),
      check("co-drain-slope", "Drainage", "Required slope to slab drains is established."),
      check("co-downspout", "Drainage", "Downspout drains within sidewalk areas are installed."),
      check("co-turndowns", "Reinforcement", "Required slab and sidewalk turndowns are installed."),
      check("co-rebar", "Reinforcement", "Correct reinforcing steel has been independently verified."),
      check("co-stubups", "Coordination", "Plumbing and electrical stub-ups are in the correct locations."),
      check("co-forms", "Formwork", "Forms are correctly installed, braced, and clean."),
      check("co-laser", "Placement", "Laser screed or laser-level requirements are confirmed."),
      choice("co-joints", "Joints", "Joint method is confirmed.", ["Tooled Joints", "Saw Cuts", "Combination", "Not Applicable"]),
      ...closeout("co"),
    ],
  },
  {
    id: "crane",
    title: "Pre-Crane Meeting",
    shortTitle: "Crane",
    sourceDocument: "Pre-Crane Meeting.pdf",
    timing: "One week before every crane pick and after any unsatisfactory attempt",
    questions: [
      check("cr-safety", "Planning & Safety", "Site coordination and crane safety concerns have been addressed."),
      check("cr-photo", "Equipment", "A current photograph of the crane has been captured."),
      check("cr-log", "Documentation", "The crane operator has a current daily logbook onsite."),
      check("cr-inspection", "Documentation", "The latest crane safety inspection report is onsite."),
      check("cr-cco", "Qualifications", "Crane operator CCO certification is current and documented."),
      check("cr-rigger", "Qualifications", "Rigger certification is current and documented."),
      check("cr-signaler", "Qualifications", "Signaler certification is current and documented."),
      check("cr-placement", "Lift Plan", "Crane placement and any multiple pick points are confirmed."),
      check("cr-swing", "Lift Plan", "The full swing area is clear inside and outside the site."),
      check("cr-obstacles", "Lift Plan", "Obstacles and overhead power lines are identified and controlled."),
      check("cr-trades", "Coordination", "Affected trades and site activities are coordinated."),
      check("cr-weather", "Lift Plan", "Weather is appropriate for the planned crane operation."),
      check("cr-capacity", "Lift Plan", "Crane configuration can safely handle the estimated load."),
      check("cr-cog", "Lift Plan", "Load center of gravity is known and the hook can remain directly above it."),
      check("cr-demo", "Logistics", "Demolished items from the pick will be removed from site."),
      check("cr-support", "Readiness", "Roof curbs, steel supports, and structural bracing are in place."),
      check("cr-traffic", "Public Protection", "Roadway blocking and traffic-control resources are assigned."),
      check("cr-outrigger", "Ground Conditions", "Outrigger bearing surface and load limits are verified."),
      check("cr-roof-plan", "Safety", "A roof safety and fall-protection plan is in place."),
      check("cr-notice", "Communication", "Everyone affected by the crane operation has been notified."),
    ],
  },
  {
    id: "demolition",
    title: "Pre-Demo Meeting",
    shortTitle: "Demolition",
    sourceDocument: "Pre-Demo Meeting.pdf",
    timing: "Before every demolition phase and after any unsatisfactory attempt",
    questions: [
      check("de-safety", "Planning & Safety", "Site coordination and safety concerns have been addressed."),
      check("de-shutoff", "Utilities", "All utility shutoff locations are known."),
      check("de-shoring", "Structural", "Required shoring has been identified and engineered."),
      check("de-bud", "Utilities", "BUD/811 locating is complete."),
      check("de-abatement", "Hazardous Materials", "Required abatement is complete and documented."),
      check("de-dust", "Environmental", "Dust-control methods are established."),
      check("de-partitions", "Protection", "Required temporary partitions are installed."),
      check("de-noise", "Environmental", "Noise, vibration, and odor precautions are established."),
      check("de-overhead", "Safety", "Overhead-line hazards are controlled."),
      check("de-dumpster", "Logistics", "Required dumpsters are onsite and correctly located."),
      check("de-permits", "Documentation", "All demolition permits are issued."),
      check("de-salvage", "Scope", "Salvage material and ownership are identified."),
      check("de-scope", "Scope", "Detailed demolition scope has been reviewed with the subcontractor."),
      check("de-equipment", "Means & Methods", "Demolition equipment and access are confirmed."),
      check("de-hours", "Operations", "Special work-hour restrictions are confirmed."),
      check("de-plan", "Safety", "The demolition safety plan is in place."),
      check("de-protection", "Protection", "Non-demolition areas and finishes are protected."),
      check("de-coordination", "Coordination", "Affected trades and activities are coordinated."),
      check("de-containment", "Environmental", "Required containment is complete."),
      check("de-extinguishers", "Life Safety", "Fire extinguishers are available and their locations are known."),
      check("de-outages", "Utilities", "Required utility outages have been requested and confirmed."),
      check("de-loto", "Utilities", "Lockout/tagout controls are in place."),
      check("de-detectors", "Life Safety", "Temporary heat-detection requirements are satisfied."),
      check("de-ppe", "Safety", "Required PPE is available and in use."),
      check("de-public", "Public Protection", "Public protection and separation are installed."),
    ],
  },
  {
    id: "drywall",
    title: "Pre-Drywall Meeting",
    shortTitle: "Drywall",
    sourceDocument: "Pre-Drywall Meeting.pdf",
    timing: "Before wall or ceiling board installation and after any unsatisfactory attempt",
    questions: [
      ...standard("dw"),
      check("dw-fastening", "Installation", "Fastening method and screw pattern are confirmed."),
      check("dw-critical", "Layout", "Critical dimensions, including ADA spaces, are verified."),
      check("dw-vents", "Protection", "Cleanup and protection of vents and ducts are established."),
      check("dw-firecaulk", "Life Safety", "Fire caulking, collars, and required horizontal hole sealing are complete."),
      check("dw-frame-inspection", "Inspection", "Required framing inspection has occurred."),
      check("dw-special-board", "Material", "Sound, abuse-resistant, wet-location, and other specialty board is identified."),
      check("dw-insulation", "Assembly", "Insulation requirements are complete before closure."),
      check("dw-tearaway", "Finish", "Tear-away bead locations are confirmed."),
      check("dw-bracing", "Framing", "Metal walls are properly braced."),
      check("dw-blocking", "Framing", "All fire, accessory, cabinet, storefront, door-stop, and equipment blocking is installed."),
      check("dw-mep", "Coordination", "MEP, low-voltage, and sprinkler rough-in matches current plans."),
      check("dw-guards", "Protection", "Stud guards are installed where required."),
      check("dw-plumb", "Framing", "Framed walls are level and plumb."),
      check("dw-nailers", "Framing", "Required nailers are installed."),
      check("dw-openings", "Framing", "Rough openings are flush and correctly sized."),
      check("dw-hangers", "Coordination", "Required hangers are installed."),
      check("dw-floor-gap", "Installation", "Drywall will not be installed tight to the floor."),
      check("dw-dampers", "Life Safety", "Required fire dampers are installed."),
      check("dw-shadowbox", "Finish", "Items requiring shadow boxes are identified."),
      check("dw-thermostat", "Coordination", "Thermostat rough-in and installation are coordinated."),
      check("dw-photos", "Evidence", "Pre-installation photographs have been captured."),
      ...closeout("dw"),
    ],
  },
  {
    id: "fire-sprinkler",
    title: "Pre-Fire Sprinkler Meeting",
    shortTitle: "Fire Sprinkler",
    sourceDocument: "Pre-Fire Sprinkler Meeting.pdf",
    timing: "Before sprinkler rough-in or major modification and after any unsatisfactory attempt",
    questions: [
      ...standard("fs"),
      check("fs-fastening", "Installation", "Fastening, connection, and anchoring methods are confirmed."),
      check("fs-backflow", "Layout", "Backflow-preventer location is confirmed."),
      check("fs-clearance", "Coordination", "Clearance obstacles have been resolved."),
      check("fs-emergency", "Emergency", "Emergency fire-department contact information is available."),
      check("fs-vault", "Utilities", "Required vault connections are identified."),
      check("fs-head-color", "Finish", "Sprinkler-head temperature/color selections are confirmed."),
      choice("fs-flex", "Installation", "Connection to sprinkler heads is confirmed.", ["Flexible Drop", "Hard Piped", "Combination", "Not Applicable"]),
      check("fs-freeze", "System", "Freeze-protection requirements are resolved."),
      check("fs-paint", "Protection", "Sprinkler heads are protected from paint and finish damage."),
      check("fs-compressor", "System", "Air compressor requirements for a dry system are satisfied."),
      check("fs-riser", "Layout", "Riser location is confirmed."),
      check("fs-hangers", "Support", "Hanger spacing and support are confirmed."),
      check("fs-truss", "Coordination", "Required truss blocking is installed."),
      check("fs-shutdown", "Operations", "Shutdowns for existing-system tie-in are scheduled."),
      check("fs-pressure", "System", "Available building pressure is adequate for the system."),
      check("fs-ceilings", "Coordination", "Finished ceiling heights are verified."),
      check("fs-dimensions", "Layout", "Critical dimensions are field verified."),
      ...closeout("fs"),
    ],
  },
  {
    id: "flooring",
    title: "Pre-Floor Meeting",
    shortTitle: "Flooring",
    sourceDocument: "Pre-Floor Meeting.pdf",
    timing: "Before every flooring system installation and after any unsatisfactory attempt",
    questions: [
      check("fl-safety", "Planning & Safety", "Site coordination and safety concerns have been addressed."),
      check("fl-submittals", "Planning & Safety", "Flooring submittals are approved and returned."),
      check("fl-trades", "Coordination", "Affected trades and activities are coordinated."),
      check("fl-sleeves", "Coordination", "Required penetrations and sleeves are resolved."),
      check("fl-scope", "Scope", "The subcontractor's complete scope is defined."),
      check("fl-ada", "Accessibility", "ADA transitions, slopes, and clearances are confirmed."),
      check("fl-level", "Substrate", "Subfloor levelness is verified."),
      check("fl-drain", "Substrate", "Required floor slope to drains is verified."),
      check("fl-acclimate", "Material", "Material acclimation requirements are being met."),
      check("fl-moisture", "Substrate", "Moisture testing and barrier requirements are satisfied."),
      check("fl-transitions", "Layout", "Flooring transitions occur under doors or at approved locations."),
      check("fl-control", "Layout", "Control and movement joints are addressed."),
      check("fl-direction", "Layout", "Hardwood direction is confirmed."),
      check("fl-pattern", "Layout", "Flooring layout and pattern are approved."),
      check("fl-jambs", "Coordination", "Door jamb and casing undercuts are complete."),
      check("fl-doors", "Coordination", "Required door-bottom trimming is identified."),
      check("fl-grout", "Finish", "Tile grout selection and sealing requirements are confirmed."),
      check("fl-underlayment", "Assembly", "Required underlayment is installed or available."),
      check("fl-finish", "Finish", "Sheen, stain, gloss, and final finish are confirmed."),
      check("fl-expansion", "Installation", "Required expansion space is established."),
      check("fl-capability", "Material", "Product limitations and intended use are confirmed."),
      check("fl-cabinets", "Coordination", "Installation under cabinets, toilets, and equipment is resolved."),
      ...closeout("fl"),
    ],
  },
  {
    id: "framing",
    title: "Pre-Framing Meeting",
    shortTitle: "Framing",
    sourceDocument: "Pre-Framing Meeting.pdf",
    timing: "Before each framing phase and after any unsatisfactory attempt",
    questions: [
      ...standard("fr"),
      check("fr-docs", "Documents", "Current construction, truss, cabinet, and related drawings are onsite."),
      check("fr-lumber", "Material", "Required structural, graded, stamped, and fire-rated lumber is identified."),
      check("fr-start", "Layout", "Starting point, stud spacing, and stacked stud alignment are established."),
      check("fr-plate", "Material", "Treated bottom plate and sill-sealer requirements are confirmed."),
      check("fr-welded", "Openings", "Welded door and window frames are identified."),
      check("fr-loadpath", "Structure", "Load-bearing points align continuously to the foundation."),
      check("fr-topplates", "Structure", "Double-top-plate joints are offset at least 24 inches."),
      check("fr-ceilings", "Code", "Sloped-ceiling habitable-area height requirements are satisfied."),
      check("fr-bracing", "Safety", "Wall stabilization and temporary bracing are established."),
      check("fr-fastening", "Structure", "Fastening, anchoring, hanger, and connector methods are confirmed."),
      check("fr-schedule", "Structure", "The required fastening schedule is being followed."),
      check("fr-hanger-holes", "Structure", "All required hanger nail holes are filled."),
      check("fr-hazards", "Safety", "Overhead power and fall-protection hazards are controlled."),
      check("fr-headers", "Structure", "Bearing and nonbearing header sizes and materials are confirmed."),
      check("fr-stairs", "Code", "Stair riser and tread dimensions comply with the approved code criteria."),
      check("fr-uniform", "Code", "Stair treads and risers are uniform within allowable tolerance."),
      check("fr-floor-heights", "Layout", "All finish-floor heights are verified."),
      check("fr-handrail-required", "Code", "Handrail and guard requirements are identified."),
      check("fr-handrail-dim", "Code", "Handrail clearance and height are confirmed."),
      check("fr-headroom", "Code", "Required stair headroom is provided."),
      check("fr-understairs", "Life Safety", "Accessible enclosed space below stairs has required protection."),
      check("fr-critical", "Layout", "Critical dimensions, including ADA spaces, are verified."),
      check("fr-attic", "Access", "Attic access clear opening is at least 22 by 30 inches where required."),
      check("fr-rough-openings", "Openings", "Door, window, tub, shower, soffit, duct, and drain rough openings are coordinated."),
      check("fr-tempered", "Glazing", "Tempered-glass locations are identified."),
      check("fr-notches", "Structure", "Structural-member cuts and notches comply with limits or engineer direction."),
      check("fr-metal-openings", "Openings", "Metal-stud door and window openings include required wood reinforcement."),
      check("fr-sheathing", "Structure", "Decking and sheathing type, orientation, fastening, adhesive, and clips are confirmed."),
      check("fr-blocking", "Coordination", "Fire, cabinet, accessibility, storefront, accessory, equipment, and finish blocking is installed."),
      check("fr-dissimilar", "Assembly", "Dissimilar materials have required isolation or vibration buffer."),
      check("fr-wrap", "Weather Barrier", "Building wrap is installed to manufacturer requirements."),
      check("fr-fascia", "Exterior", "Freeze board, fascia, and soffit details are confirmed."),
      check("fr-trim", "Finish", "Trim type and attachment to framing are confirmed."),
      check("fr-large-items", "Coordination", "Large items that must precede framing are onsite and installed."),
      check("fr-insulation", "Energy", "Required wall, floor, and attic insulation values are confirmed."),
      ...closeout("fr"),
    ],
  },
  {
    id: "sitework",
    title: "Pre-Grading / Utilities / Paving / Landscaping Meeting",
    shortTitle: "Sitework",
    sourceDocument: "Pre-Grading-Utilities-Paving-Landscaping Meeting.pdf",
    timing: "Before each applicable sitework phase and after any unsatisfactory attempt",
    questions: [
      ...standard("sw"),
      check("sw-bud", "Utilities", "BUD/811 has been contacted."),
      check("sw-utilities", "Utilities", "Other affected utility companies have been contacted."),
      check("sw-asbuilts", "Existing Conditions", "Owner-provided as-builts have been obtained and reviewed."),
      check("sw-septic", "Existing Conditions", "Existing septic systems are located and protected."),
      choice("sw-pipe", "Utilities", "Required piping is confirmed.", ["Schedule 40", "Schedule 80", "Other Approved Material", "Not Applicable"]),
      check("sw-depth", "Utilities", "Utility depths are verified."),
      check("sw-bedding", "Utilities", "Pipe bedding and backfill requirements are confirmed."),
      check("sw-spares", "Utilities", "Required spare conduits are identified."),
      check("sw-tracer", "Utilities", "Required marking tape and tracer wire are provided."),
      check("sw-shoring", "Excavation", "Excavation shoring or layback requirements are established."),
      check("sw-boots", "Drainage", "Downspout boot requirements are confirmed."),
      check("sw-proofroll", "Earthwork", "Proof-roll and compaction testing are complete or scheduled."),
      check("sw-drains", "Drainage", "Yard and French drain requirements are confirmed."),
      check("sw-soil", "Landscaping", "Landscape soil mixture is confirmed."),
      check("sw-seed", "Landscaping", "Seed mixture and installation requirements are confirmed."),
      check("sw-spacing", "Utilities", "Required separation between electric, water, sewer, and communications is maintained."),
      check("sw-maintenance", "Closeout", "Landscape maintenance period and warranty are defined."),
      check("sw-easements", "Layout", "Utility easements are known and protected."),
      check("sw-drainage", "Drainage", "Water shedding from surrounding property is understood and addressed."),
      check("sw-irrigation", "Landscaping", "Irrigation/sprinkler coverage is coordinated."),
      check("sw-ada", "Accessibility", "ADA sitework requirements are verified."),
      check("sw-critical", "Layout", "Critical site dimensions and grades are verified."),
      ...closeout("sw"),
    ],
  },
  {
    id: "masonry",
    title: "Pre-Masonry Meeting",
    shortTitle: "Masonry",
    sourceDocument: "Pre-Masonry Meeting.pdf",
    timing: "Before masonry installation or repair and after any unsatisfactory attempt",
    questions: [
      ...standard("ma"),
      check("ma-frames", "Openings", "Welded frames and door/window setting responsibilities are confirmed."),
      check("ma-bracing", "Safety", "Wall stabilization and temporary bracing are established."),
      check("ma-openings", "Openings", "Door, window, and penetration rough openings are coordinated."),
      check("ma-fascia", "Exterior", "Freeze board, fascia, and soffit details are confirmed."),
      check("ma-flashing", "Water Management", "Flashing, mortar net, weeps, vents, ties, and reinforcing details are confirmed."),
      check("ma-lintel", "Structure", "Lintel schedule and bearing are confirmed."),
      check("ma-ledge", "Structure", "Brick-ledge details are verified."),
      check("ma-bond", "Structure", "Required bond beams are identified."),
      check("ma-fill", "Structure", "Required block cells are fully grouted/slush filled."),
      check("ma-airgap", "Assembly", "Required masonry air-space dimension is maintained."),
      check("ma-tooth", "Finish", "Toothing and joint details are confirmed."),
      check("ma-insulation", "Energy", "Required insulation within or outside the block is coordinated."),
      check("ma-stone", "Finish", "Decorative stone, water tables, sills, caps, and keystones are confirmed."),
      check("ma-wash", "Finish", "Masonry cleaning and acid-wash requirements are established."),
      check("ma-seal", "Finish", "Brick and masonry sealer requirements are confirmed."),
      check("ma-expansion", "Movement", "Expansion-joint locations and caulking responsibility are confirmed."),
      check("ma-removal", "Safety", "Support required for masonry removal and replacement is established."),
      check("ma-dust", "Environmental", "Grinding and tuck-pointing dust is controlled."),
      check("ma-mortar", "Finish", "Mortar color match and measured batch consistency are confirmed."),
      check("ma-crawl", "Layout", "Required crawl-space dimensions and access are verified."),
      ...closeout("ma"),
    ],
  },
  {
    id: "painting",
    title: "Pre-Painting Meeting",
    shortTitle: "Painting",
    sourceDocument: "Pre-Painting Meeting.pdf",
    timing: "Before each painting or coating phase and after any unsatisfactory attempt",
    questions: [
      check("pa-safety", "Planning & Safety", "Site coordination and safety concerns have been addressed."),
      check("pa-submittals", "Planning & Safety", "Paint and coating submittals are approved and returned."),
      check("pa-delivery", "Logistics", "Delivery and off-loading are established."),
      check("pa-storage", "Logistics", "Staging, storage, and protection are established."),
      check("pa-finish", "Finish", "Sheen and finish selections are confirmed."),
      check("pa-caulk", "Scope", "Caulking locations and responsible trade are confirmed."),
      check("pa-plates", "Protection", "Electrical plates and switch covers are removed where required."),
      check("pa-sprinkler", "Protection", "Sprinkler heads are protected."),
      check("pa-film", "Preparation", "Protective film and tape that would interfere with coating are removed."),
      check("pa-doors", "Scope", "Painting of door tops and bottoms is defined."),
      check("pa-prepaint", "Scope", "Materials requiring pre-painting are identified."),
      check("pa-alarm", "Life Safety", "Fire-alarm systems and detectors are protected and coordinated."),
      check("pa-weather", "Application", "Temperature and weather are appropriate for the coating system."),
      check("pa-sds", "Safety", "Current SDS sheets have been provided."),
      check("pa-sanding", "Finish", "Required sanding between coats is defined."),
      check("pa-clean", "Preparation", "Surfaces and surroundings are clean before coating."),
      check("pa-protect", "Protection", "Surrounding surfaces and areas are properly protected."),
      check("pa-operable", "Quality", "Windows, doors, and other operable items function before coating."),
      check("pa-cleanup", "Completion", "Cleanup responsibilities are established."),
    ],
  },
  {
    id: "roofing",
    title: "Pre-Roof Meeting",
    shortTitle: "Roofing",
    sourceDocument: "Pre-Roof Meeting.pdf",
    timing: "Before each roofing system installation and after any unsatisfactory attempt",
    questions: [
      ...standard("ro"),
      check("ro-fastening", "Installation", "Fastening, connection, and anchoring methods are confirmed."),
      check("ro-hazards", "Safety", "Overhead power and fall-protection hazards are controlled."),
      check("ro-blocking", "Structure", "Required fire, sheathing, ridge-vent, and specialty blocking is installed."),
      check("ro-penetrations", "Coordination", "All roof penetrations are located and validated."),
      check("ro-crickets", "Drainage", "Required framed crickets are identified."),
      check("ro-drainage", "Drainage", "Gutters, downspouts, scuppers, and box gutters are coordinated."),
      check("ro-termination", "Installation", "Termination-bar requirements are confirmed."),
      check("ro-drip", "Installation", "Drip-edge requirements are confirmed."),
      check("ro-parapet", "Exterior", "Parapet-wall and coping details are confirmed."),
      check("ro-snow", "Safety", "Snow-guard requirements are confirmed."),
      check("ro-taper", "Drainage", "Tapered-insulation layout is confirmed."),
      check("ro-lightweight", "Assembly", "Lightweight-concrete roof-deck conditions are addressed."),
      check("ro-drains", "Drainage", "Roof-drain locations and elevations are confirmed."),
      check("ro-flashing", "Waterproofing", "Flashing details are reviewed and coordinated."),
      check("ro-vent", "Ventilation", "Ridge-vent and roof-ventilation requirements are confirmed."),
      check("ro-curbs", "Coordination", "Roof hatches, skylights, and HVAC curbs are installed and ready."),
      check("ro-seams", "Waterproofing", "Membrane seam overlap and installation direction are confirmed."),
      check("ro-warranty", "Warranty", "Manufacturer warranty inspection requirements are scheduled."),
      ...closeout("ro"),
    ],
  },
  {
    id: "trenching-excavation",
    title: "Pre-Trenching / Excavation Checklist",
    shortTitle: "Trenching & Excavation",
    sourceDocument: "Pre-Trnching_Excavation Checklist.pdf",
    timing: "Before each excavation condition or location and after any unsatisfactory attempt",
    questions: [
      text("te-depth", "Excavation Profile", "Estimated trench depth, length, and width"),
      check("te-facilities-meeting", "Utilities", "An onsite meeting is scheduled with high-profile facility owners in the locate area."),
      check("te-emergency", "Emergency", "Emergency contact numbers for utilities in and adjacent to the dig zone are readily available."),
      check("te-competent", "Competent Person", "A competent person is assigned to the site."),
      text("te-competent-name", "Competent Person", "Name of assigned competent person"),
      check("te-white", "Utilities", "The proposed excavation is marked in white paint and/or flags."),
      check("te-811", "Utilities", "811 has been contacted."),
      check("te-marked", "Utilities", "All utility owners have responded and facilities are marked."),
      check("te-ticket-scope", "Utilities", "The 811 ticket covers the full scope and has a valid work-to-begin date."),
      check("te-ticket-posted", "Utilities", "The 811 ticket number is posted at the work location."),
      check("te-private", "Utilities", "Private facilities not covered by 811 have been located and marked."),
      check("te-tolerance", "Utilities", "Utility tolerance zones are marked and hand-dig requirements are understood."),
      check("te-analysis", "Soil", "Required soil analysis and classification are complete."),
      choice("te-analysis-method", "Soil", "Soil analysis method is confirmed.", ["Visual", "Manual", "Chemical", "Combination", "Not Applicable"]),
      check("te-contaminants", "Soil", "Soil contaminants have been evaluated and controlled."),
      check("te-system", "Protective System", "A protective system has been selected."),
      choice("te-system-type", "Protective System", "Protective system is confirmed.", ["Hydraulic Shoring", "Shielding / Trench Box", "Soldier Sets", "Battering", "Sloping / Benching", "Not Required"]),
      check("te-manufacturer", "Protective System", "Manufacturer information confirms the protective system is adequate for the job."),
      check("te-equipment", "Protective System", "The competent person inspected protective-system materials and equipment."),
      check("te-spoils", "Excavation", "Spoils placement is established at least two feet from the opening."),
      check("te-egress", "Access", "Safe egress is provided."),
      check("te-accessible", "Access", "All personnel can reasonably use the access and egress."),
      check("te-rescue", "Emergency", "Personnel know emergency, rescue, and evacuation procedures."),
      check("te-traffic", "Public Protection", "A traffic-control plan is established."),
      check("te-air", "Confined Space", "Air-monitoring equipment is available when the excavation may be a confined space."),
      check("te-water", "Water Control", "Drainage or pumping is available when water accumulation is expected."),
      check("te-crossing", "Access", "Required surface crossings and railings comply with OSHA requirements."),
      check("te-training", "Training", "Employees working in the excavation area are properly trained."),
      check("te-barrier", "Public Protection", "Fences or barriers prevent unauthorized entry when the excavation is unattended."),
      check("te-ppe", "Safety", "Hard hats and all required PPE are worn."),
      check("te-loose-material", "Safety", "Employees are protected from loose rock or soil falling or rolling into the excavation."),
    ],
  },
  {
    id: "windows-doors",
    title: "Pre-Window / Door Installation",
    shortTitle: "Windows & Doors",
    sourceDocument: "Pre-Window-Door Installation.pdf",
    timing: "Before each window or door installation phase and after any unsatisfactory attempt",
    questions: [
      ...standard("wd"),
      check("wd-security", "Coordination", "Keyless entry, security, and glass-break devices are coordinated."),
      check("wd-large", "Logistics", "Large materials that must precede enclosure are inside the building."),
      check("wd-frame", "Material", "Door and window frame types are confirmed."),
      check("wd-key", "Hardware", "Key schedule is available."),
      check("wd-core", "Hardware", "Master-core requirements are confirmed."),
      check("wd-interference", "Layout", "Door-swing interferences are resolved."),
      check("wd-swing", "Layout", "Door swings match the current plans."),
      check("wd-openings", "Openings", "Openings are square, plumb, and at correct elevations."),
      check("wd-header", "Openings", "Header heights from finish floor are correct."),
      check("wd-flashing", "Waterproofing", "Flashing and flexible-flashing details are correct."),
      check("wd-blocking", "Openings", "Required wood blocking is installed."),
      check("wd-insulation", "Energy", "Perimeter insulation requirements are satisfied."),
      check("wd-bolts", "Hardware", "Foot- and head-bolt requirements are confirmed."),
      check("wd-floor", "Coordination", "Finish-floor material and its effect on installation are resolved."),
      check("wd-access", "Logistics", "Remaining building materials can be moved inside after enclosure."),
      check("wd-millwork", "Finish", "Finish millwork material is confirmed."),
      check("wd-pocket", "Installation", "Pocket-door spacers and travel clearance are installed."),
      check("wd-remodel", "Existing Conditions", "New versus renovation opening conditions are confirmed."),
      check("wd-hardware", "Hardware", "Locksets, closers, spring hinges, panic hardware, and stops are confirmed."),
      check("wd-weatherstrip", "Energy", "Weather-stripping requirements are confirmed."),
      check("wd-storm", "Exterior", "Storm doors and windows are identified."),
      check("wd-bevel", "Installation", "Door bevel supports the correct swing direction."),
      check("wd-air", "Mechanical", "Required return or supply-air transfer below doors is coordinated."),
      check("wd-firedoor", "Life Safety", "Rolling fire-door requirements are identified."),
      check("wd-glass", "Glazing", "Glass type and fire/tempered locations are confirmed."),
      check("wd-ada", "Accessibility", "ADA opening, hardware, threshold, and maneuvering requirements are confirmed."),
      ...closeout("wd"),
    ],
  },
  {
    id: "fireproofing",
    title: "Pre-Fireproofing Checklist",
    shortTitle: "Fireproofing",
    sourceDocument: "FIREPROOFING CL-04.24.24.docx",
    timing: "Before drywall walls and again before ceiling installation; repeat after any unsatisfactory attempt",
    questions: [
      ...standard("fp"),
      check("fp-meps", "Coordination", "The checklist has been coordinated with every affected MEP and sprinkler trade."),
      choice("fp-rating", "Rated Assemblies", "Required wall rating is confirmed.", ["1 Hour", "2 Hour", "Multiple Ratings", "Not Applicable"]),
      check("fp-areas", "Rated Assemblies", "Shafts, stairs, corridors, tenant separations, and equipment rooms have correct ratings."),
      choice("fp-class", "Rated Assemblies", "Assembly classification is confirmed.", ["Fire Wall", "Fire Barrier", "Fire Partition", "Multiple Classifications", "Not Applicable"]),
      check("fp-visible", "Inspection", "The work remains visible and accessible for inspection before concealment."),
      check("fp-sealed", "Continuity", "Rated walls are completely sealed to floors, walls, and structure."),
      check("fp-penetrations", "Penetrations", "Penetration openings and annular spaces are acceptable."),
      check("fp-substrate", "Substrate", "Substrate condition is acceptable for the listed system."),
      check("fp-ahj", "Code", "Applicable code and AHJ requirements are confirmed."),
      check("fp-compatible", "Material", "MEP and sprinkler materials are compatible with the rated assembly."),
      text("fp-ul", "Listed Systems", "UL or other listed assembly number by location"),
      choice("fp-method", "Listed Systems", "Penetration-sealing method is confirmed.", ["Rock Wool + Fire Caulk", "Fire Caulk", "Fire Spray", "Fire Collar", "Multiple Listed Systems"]),
      check("fp-application", "Listed Systems", "Correct listed material and application thickness are available."),
      check("fp-weather", "Application", "Temperature, weather, and atmosphere are suitable for application."),
      ...closeout("fp"),
    ],
  },
  {
    id: "pre-engineered-metal-building",
    title: "Pre-Metal Building Checklist",
    shortTitle: "Metal Building",
    sourceDocument: "PRE METAL BUILDING CHECKLIST.docx",
    timing: "Before erection and again after any unsatisfactory attempt",
    questions: [
      ...standard("mb"),
      check("mb-foundation", "Layout", "Foundation dimensions, anchor-bolt locations, and bolt diameters are verified."),
      check("mb-parts", "Material", "All parts are onsite and reconciled to manufacturer tally sheets."),
      check("mb-equipment", "Equipment", "Cranes, forklifts, and manlifts have current safety inspections and correct lifting attachments."),
      check("mb-paths", "Logistics", "Equipment paths and lift-area access are clear."),
      check("mb-fall", "Safety", "Tie-off, power-line, and equipment-capacity requirements are reviewed."),
      check("mb-tools", "Electrical Safety", "GFCI-protected cords and task-appropriate tools are available."),
      check("mb-guide", "Documents", "The manufacturer's erection guide is onsite and reviewed."),
      check("mb-modify", "Structure", "No framing member will be cut or modified without written manufacturer direction."),
      check("mb-columns-safe", "Erection", "Column anchor bolts are tightened and columns will never be left unattended while unbolted."),
      check("mb-plan-location", "Layout", "All components are placed according to the building plans."),
      check("mb-openings", "Openings", "Door and window openings match the plans and will not be relocated without written approval."),
      check("mb-columns", "Erection", "Columns are plumb, tightly bolted, and braced."),
      check("mb-purlins", "Erection", "Purlin and girt bolts, clips, and hangers meet manufacturer requirements."),
      check("mb-insulation", "Envelope", "Insulation type and thickness are correct before installation."),
      check("mb-liner", "Envelope", "Liner-panel type, color, length, and trims are correct."),
      check("mb-closures", "Envelope", "Closure strips, mastics, and clips match the plans."),
      check("mb-screws", "Envelope", "Panel screws will not be overtightened and damaged screws will be replaced."),
      check("mb-count", "Envelope", "Manufacturer-required panel screw counts are followed."),
      check("mb-standing", "Roof", "Standing-seam roof channels are locked to manufacturer standards."),
      check("mb-downspouts", "Drainage", "Downspout count and layout match the plans."),
      check("mb-special", "Inspection", "Required special inspections and bolt-tightness checks are scheduled."),
      check("mb-cleanup", "Completion", "Site cleanup and recovery of unused material are planned."),
    ],
  },
];

export const SCHEDULE_QUALITY_CATEGORIES: ScheduleQualityCategory[] = [
  ...PREWORK_QUALITY_TEMPLATES.map((template) => ({
    id: template.id,
    label: template.shortTitle,
    templateId: template.id,
    leadDays: template.id === "crane" ? 7 : template.id === "trenching-excavation" ? 5 : 3,
  })),
  { id: "general-administrative", label: "General / Administrative", templateId: "", leadDays: 0 },
  { id: "closeout-commissioning", label: "Closeout / Commissioning", templateId: "", leadDays: 0 },
];

export function scheduleQualityCategory(id: string) {
  return SCHEDULE_QUALITY_CATEGORIES.find((category) => category.id === id) || null;
}

export function qualityChecklistDueDate(activityStart: string, categoryId: string) {
  const category = scheduleQualityCategory(categoryId);
  if (!category?.templateId || !/^\d{4}-\d{2}-\d{2}$/.test(activityStart)) return "";
  const due = new Date(`${activityStart}T12:00:00Z`);
  due.setUTCDate(due.getUTCDate() - category.leadDays);
  return due.toISOString().slice(0, 10);
}

export type QualityResponse = { questionId: string; answer: string; note: string };

export function templateById(id: string) {
  return PREWORK_QUALITY_TEMPLATES.find((template) => template.id === id) || null;
}

export function inspectionResult(template: QualityTemplate, responses: QualityResponse[]) {
  const responseMap = new Map(responses.map((response) => [response.questionId, response]));
  const incomplete = template.questions.filter((question) => !responseMap.get(question.id)?.answer.trim());
  const failed = template.questions.filter((question) => question.input === "check" && responseMap.get(question.id)?.answer === "No");
  const unjustifiedNa = template.questions.filter((question) => question.input === "check" && responseMap.get(question.id)?.answer === "N/A" && !responseMap.get(question.id)?.note.trim());
  return { complete: incomplete.length === 0 && unjustifiedNa.length === 0, incomplete, failed, unjustifiedNa, satisfactory: incomplete.length === 0 && unjustifiedNa.length === 0 && failed.length === 0 };
}

export function parseQualityData(value: string): Record<string, unknown> {
  try {
    const parsed = JSON.parse(value) as unknown;
    return parsed && typeof parsed === "object" && !Array.isArray(parsed) ? parsed as Record<string, unknown> : {};
  } catch {
    return {};
  }
}

export function normalizeStringArray(value: unknown) {
  return Array.isArray(value) ? value.map(String).filter(Boolean) : [];
}
